Repository waldreg/waldreg-api, pull requests merged in 2023-05, with the labels that each got.

#426 fix : home content domain into clob
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/home/HomeContent.java
Labels: fix bug, size/XS

#427 feat : filename(origin,uuid) 조회 인수테스트
  waldreg/application-layer/acceptance/TestDocx.docx
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/board/BoardAcceptanceTest.java
  waldreg/application-layer/board-controller/src/main/java/org/waldreg/controller/board/board/mapper/ControllerBoardMapper.java
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/FileNameCommander.java
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/ReactionRepositoryServiceProvider.java
  waldreg/repository-layer/board-jpa/src/test/java/org/waldreg/repository/board/FileNameRepositoryTest.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/file/DefaultFileManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/file/spi/BoardFileNameRepository.java
  waldreg/service-layer/board/src/test/java/org/waldreg/board/file/FileManagerTest.java
Labels: fix bug, size/L

#428 [feat] : 0.7.0 파일이름조회 기능 추가
  waldreg/application-layer/acceptance/TestDocx.docx
  waldreg/application-layer/acceptance/TestDocx.msword
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/board/BoardAcceptanceTest.java
  waldreg/application-layer/board-controller/src/main/java/org/waldreg/controller/board/board/mapper/ControllerBoardMapper.java
  waldreg/application-layer/board-controller/src/main/java/org/waldreg/controller/board/board/response/BoardResponse.java
  waldreg/application-layer/board-controller/src/main/java/org/waldreg/controller/board/board/response/FileName.java
  waldreg/application-layer/board-controller/src/main/java/org/waldreg/controller/board/file/FileController.java
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/board/Board.java
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/board/file/FileName.java
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/BoardRepositoryServiceProvider.java
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/FileNameCommander.java
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/ReactionRepositoryServiceProvider.java
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/mapper/BoardRepositoryMapper.java
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/repository/JpaFileNameRepository.java
  waldreg/repository-layer/board-jpa/src/test/java/org/waldreg/repository/board/BoardRepositoryTest.java
  waldreg/repository-layer/board-jpa/src/test/java/org/waldreg/repository/board/BoardUserRepositoryTest.java
  waldreg/repository-layer/board-jpa/src/test/java/org/waldreg/repository/board/FileNameRepositoryTest.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/file/DefaultFileManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/file/DefaultFileNameManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/file/FileNameManger.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/file/spi/BoardFileNameRepository.java
  waldreg/service-layer/board/src/test/java/org/waldreg/board/file/FileManagerTest.java
Labels: size/XL
