Repository waldreg/waldreg-api, pull requests merged in 2023-02, with the labels that each got.

#189 test : board 생성 기능 추가
  waldreg/application-layer/board-controller/src/main/java/org/waldreg/controller/board/request/BoardCreateRequest.java
  waldreg/application-layer/board-controller/src/main/java/org/waldreg/controller/board/request/CategoryRequest.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/BoardManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/exception/BlankTitleException.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/management/BoardManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/management/DefaultBoardManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/dto/BoardDto.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/dto/ReactionDto.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/file/DefaultFileManager.java
  waldreg/service-layer/board/src/test/java/org/waldreg/board/board/BoardManagerTest.java
Labels: size/L

#192 feat : Schedule 완성
  README.md
  waldreg/application-layer/acceptance/build.gradle
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/schedule/ScheduleAcceptanceTest.java
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/schedule/ScheduleAcceptanceTestHelper.java
  waldreg/application-layer/schedule-controller/build.gradle
  waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/ScheduleController.java
  waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/exceptionadvice/ExceptionTemplate.java
  waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/exceptionadvice/ScheduleControllerAdvice.java
  waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/mapper/ControllerScheduleMapper.java
  waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/request/ScheduleRepeatRequest.java
  waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/request/ScheduleRequest.java
  waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/response/ScheduleListResponse.java
  waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/response/ScheduleRepeatResponse.java
  waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/response/ScheduleResponse.java
  waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/UserController.java
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/board/Board.java
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/board/comment/Comment.java
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/board/reaction/Reaction.java
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/calendar/Schedule.java
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/calendar/ScheduleRepeat.java
  waldreg/repository-layer/memory-repository/build.gradle
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryScheduleStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/schedule/MemoryScheduleRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/schedule/ScheduleMapper.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/schedule/ScheduleRepositoryTest.java
  waldreg/service-layer/schedule/build.gradle
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/config/SchedulePermissionConfigurer.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/management/DefaultScheduleManager.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/spi/ScheduleRepository.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/spi/repository/ScheduleRepository.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/spi/schedule/ScheduleIdExistChecker.java
  waldreg/service-layer/schedule/src/test/java/org/waldreg/schedule/ScheduleServiceTest.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/config/UserPermissionConfigurer.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/management/DefaultUserManager.java
  waldreg/settings.gradle
Labels: size/XXL

#193 fix : Character 서비스 예외코드 추가
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/permission/PermissionAcceptanceTest.java
  waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/exceptionadvice/CharacterControllerAdvice.java
  waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/request/CharacterRequest.java
  waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/request/PermissionRequest.java
Labels: size/S

#194 fix : REWARD 서비스에 예외 코드를 추가함
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/reward/RewardAcceptanceTest.java
  waldreg/application-layer/reward-controller/build.gradle
  waldreg/application-layer/reward-controller/src/main/java/org/waldreg/controller/reward/exceptionadvice/ExceptionTemplate.java
  waldreg/application-layer/reward-controller/src/main/java/org/waldreg/controller/reward/exceptionadvice/RewardControllerAdvice.java
  waldreg/application-layer/reward-controller/src/main/java/org/waldreg/controller/reward/tag/request/RewardTagRequest.java
Labels: fix bug, size/M

#191 feat : board 조회 기능 추가 & board 생성 기능 예외 삭제
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/exception/BlankTitleException.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/exception/BoardDoesNotExistException.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/exception/CategoryDoesNotExistException.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/exception/UserDoesNotExistException.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/management/BoardManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/management/DefaultBoardManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/spi/BoardRepository.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/spi/CategoryRepository.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/spi/UserRepository.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/dto/BoardDto.java
  waldreg/service-layer/board/src/test/java/org/waldreg/board/board/BoardManagerTest.java
Labels: size/L

#197 feat : 파일 이름 변경 서비스 추가
  waldreg/service-layer/board/src/main/java/org/waldreg/board/file/DefaultFileManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/file/FileManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/file/exception/DuplicateFileId.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/file/exception/UnknownFileId.java
  waldreg/service-layer/board/src/test/java/org/waldreg/board/file/FileManagerTest.java
Labels: feature, test, size/M

#198 feat : 파일 삭제 서비스 추가
  waldreg/service-layer/board/src/main/java/org/waldreg/board/file/DefaultFileManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/file/FileManager.java
  waldreg/service-layer/board/src/test/java/org/waldreg/board/file/FileManagerTest.java
Labels: feature, test, size/M

#200 카테고리별 전체 게시글 조회 기능 추가
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/management/BoardManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/management/DefaultBoardManager.java
  waldreg/service-layer/board/src/test/java/org/waldreg/board/board/BoardManagerTest.java
Labels: size/M

#199 feat : 파일 조회 서비스 추가
  waldreg/service-layer/board/src/main/java/org/waldreg/board/file/DefaultFileManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/file/FileManager.java
  waldreg/service-layer/board/src/test/java/org/waldreg/board/file/FileManagerTest.java
Labels: feature, test, size/M

#201 Board 검색 기능 추가
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/management/BoardManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/management/DefaultBoardManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/spi/BoardRepository.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/file/DefaultFileManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/file/FileManager.java
  waldreg/service-layer/board/src/test/java/org/waldreg/board/board/BoardManagerTest.java
  waldreg/service-layer/board/src/test/java/org/waldreg/board/file/FileManagerTest.java
Labels: size/L

#205 fix : 유저 Excpetion Template 수정
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/authentication/AuthenticationAcceptanceTest.java
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/permission/PermissionAcceptanceTest.java
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/reward/RewardAcceptanceTest.java
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/schedule/ScheduleAcceptanceTest.java
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/user/UserAcceptanceTest.java
  waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/globalexceptionadvice/RequestValidationAdvice.java
  waldreg/application-layer/schedule-controller/build.gradle
  waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/exceptionadvice/ExceptionTemplate.java
  waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/exceptionadvice/ScheduleControllerAdvice.java
  waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/request/ScheduleRequest.java
  waldreg/application-layer/user-controller/build.gradle
  waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/exceptionadvice/ExceptionTemplate.java
  waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/exceptionadvice/UserControllerAdvice.java
  waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/request/CharacterRequest.java
  waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/request/UpdateUserRequest.java
  waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/request/UserRequest.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryUserStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/user/MemoryUserRepository.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/exception/DuplicatedUserIdException.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/exception/InvalidRangeException.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/exception/UnknownIdException.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/exception/UnknownUserIdException.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/management/DefaultUserManager.java
Labels: fix bug, size/L

#206 Error hotfix auth
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/authentication/AuthenticationAcceptanceTest.java
  waldreg/application-layer/auth-controller/build.gradle
  waldreg/application-layer/auth-controller/src/main/java/org/waldreg/auth/AuthController.java
  waldreg/application-layer/auth-controller/src/main/java/org/waldreg/auth/exceptionadvice/AuthExceptionAdvice.java
  waldreg/application-layer/auth-controller/src/main/java/org/waldreg/auth/exceptionadvice/AuthExceptionTemplate.java
  waldreg/application-layer/auth-controller/src/main/java/org/waldreg/auth/request/AuthTokenRequest.java
  waldreg/service-layer/auth/src/main/java/org/waldreg/token/exception/CannotBeBlankException.java
Labels: size/L

#208 fix : Schedule Error Excpetion Template 수정
  waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/exceptionadvice/ScheduleControllerAdvice.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/exception/ContentOverflowException.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/exception/InvalidDateFormatException.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/exception/InvalidRepeatException.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/exception/InvalidSchedulePeriodException.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/exception/UnknownScheduleException.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/management/DefaultScheduleManager.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/exception/DuplicatedUserIdException.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/exception/InvalidRangeException.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/exception/UnknownIdException.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/exception/UnknownUserIdException.java
Labels: fix bug, size/M

#203 test : Create new Board repository success test
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/board/Board.java
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/board/reaction/Reaction.java
  waldreg/repository-layer/memory-repository/build.gradle
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryBoardStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/BoardMapper.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/MemoryBoardRepository.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/board/BoardRepositoryTest.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/management/BoardManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/management/DefaultBoardManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/dto/BoardDto.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/dto/BoardServiceMemberTier.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/dto/BoardServiceReactionType.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/dto/CategoryDto.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/dto/CommentDto.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/dto/ReactionDto.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/dto/UserDto.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/file/32834a5c-73b9-4aea-aad5-54da8783b88d.png
  waldreg/service-layer/board/src/test/java/org/waldreg/board/board/BoardManagerTest.java
Labels: test, size/XL

#210 Error hotfix
  README.md
  waldreg/application-layer/acceptance/build.gradle
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/authentication/AuthenticationAcceptanceTest.java
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/permission/PermissionAcceptanceTest.java
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/reward/RewardAcceptanceTest.java
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/schedule/ScheduleAcceptanceTest.java
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/user/UserAcceptanceTest.java
  waldreg/application-layer/application-configurer/build.gradle
  waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/globalexceptionadvice/ExceptionTemplate.java
  waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/globalexceptionadvice/RequestValidationAdvice.java
  waldreg/application-layer/auth-controller/build.gradle
  waldreg/application-layer/auth-controller/src/main/java/org/waldreg/auth/AuthController.java
  waldreg/application-layer/auth-controller/src/main/java/org/waldreg/auth/exceptionadvice/AuthExceptionAdvice.java
  waldreg/application-layer/auth-controller/src/main/java/org/waldreg/auth/exceptionadvice/AuthExceptionTemplate.java
  waldreg/application-layer/auth-controller/src/main/java/org/waldreg/auth/request/AuthTokenRequest.java
  waldreg/application-layer/character-controller/build.gradle
  waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/exceptionadvice/CharacterControllerAdvice.java
  waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/exceptionadvice/ExceptionTemplate.java
  waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/request/CharacterRequest.java
  waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/request/PermissionRequest.java
  waldreg/application-layer/reward-controller/build.gradle
  waldreg/application-layer/reward-controller/src/main/java/org/waldreg/controller/reward/exceptionadvice/ExceptionTemplate.java
  waldreg/application-layer/reward-controller/src/main/java/org/waldreg/controller/reward/exceptionadvice/RewardControllerAdvice.java
  waldreg/application-layer/reward-controller/src/main/java/org/waldreg/controller/reward/tag/request/RewardTagRequest.java
  waldreg/application-layer/schedule-controller/build.gradle
  waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/exceptionadvice/ExceptionTemplate.java
  waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/exceptionadvice/ScheduleControllerAdvice.java
  waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/request/ScheduleRequest.java
  waldreg/application-layer/user-controller/build.gradle
  waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/exceptionadvice/ExceptionTemplate.java
  waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/exceptionadvice/UserControllerAdvice.java
  waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/request/CharacterRequest.java
  waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/request/UpdateUserRequest.java
  waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/request/UserRequest.java
  waldreg/core-layer/template/build.gradle
  waldreg/core-layer/template/src/main/java/org/waldreg/core/template/exception/ExceptionTemplate.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryUserStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/user/MemoryUserRepository.java
  waldreg/service-layer/auth/src/main/java/org/waldreg/token/exception/CannotBeBlankException.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/exception/ContentOverflowException.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/exception/InvalidDateFormatException.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/exception/InvalidRepeatException.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/exception/InvalidSchedulePeriodException.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/exception/UnknownScheduleException.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/management/DefaultScheduleManager.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/exception/DuplicatedUserIdException.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/exception/InvalidRangeException.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/exception/UnknownIdException.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/exception/UnknownUserIdException.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/management/DefaultUserManager.java
  waldreg/settings.gradle
  waldreg/stable-service-layer/character/build.gradle
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/permission/management/PermissionUnitManager.java
Labels: size/XL

#207 feat : board Repository 생성기능 추가 & style : Dto 스타일 수정
  waldreg/application-layer/board-controller/src/main/java/org/waldreg/controller/board/request/CategoryRequest.java
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/board/Board.java
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/board/reaction/Reaction.java
  waldreg/repository-layer/memory-repository/build.gradle
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryBoardStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/BoardMapper.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/MemoryBoardRepository.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/board/BoardRepositoryTest.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/management/BoardManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/management/DefaultBoardManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/category/CategoryManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/category/exception/DuplicateCategoryNameException.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/category/management/CategoryManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/category/management/DefaultCategoryManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/category/spi/CategoryRepository.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/dto/BoardDto.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/dto/BoardServiceMemberTier.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/dto/BoardServiceReactionType.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/dto/CategoryDto.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/dto/CommentDto.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/dto/ReactionDto.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/dto/UserDto.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/file/32834a5c-73b9-4aea-aad5-54da8783b88d.png
  waldreg/service-layer/board/src/main/java/org/waldreg/board/file/a591bde1-9081-41e3-81fd-a9c21ea5ce31.png
  waldreg/service-layer/board/src/test/java/org/waldreg/board/board/BoardManagerTest.java
  waldreg/service-layer/board/src/test/java/org/waldreg/board/category/CategoryManagerTest.java
Labels: size/XL

#212 fix : 새로운 보드 생성 성공 레포지토리 테스트
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryBoardStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/BoardMapper.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/board/BoardRepositoryTest.java
Labels: test, size/M

#214 refactor : memberTier 삭제
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/board/Board.java
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/category/Category.java
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/tier/MemberTier.java
Labels: refactor, size/M

#213 feat : category 전체조회, 수정 기능 추가
  waldreg/service-layer/board/src/main/java/org/waldreg/board/category/exception/CategoryDoesNotExistException.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/category/exception/DuplicateCategoryNameException.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/category/management/CategoryManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/category/management/DefaultCategoryManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/category/spi/BoardRepository.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/category/spi/CategoryRepository.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/category/spi/UserRepository.java
  waldreg/service-layer/board/src/test/java/org/waldreg/board/category/CategoryManagerTest.java
Labels: size/L

#215 Board repository
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/board/Board.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryBoardStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/BoardMapper.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/MemoryBoardRepository.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/board/BoardRepositoryTest.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/spi/BoardRepository.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/dto/CategoryDto.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/file/3509d378-f0b9-4e5c-943a-1bde663620c9.png
  waldreg/service-layer/board/src/main/java/org/waldreg/board/file/c387fa90-2ea9-4b0e-b4fc-137fa14d5ec3.png
  waldreg/service-layer/board/src/test/java/org/waldreg/board/board/BoardManagerTest.java
Labels: test, size/L

#218 refactor : 파일,이미지 저장방식 변경 …
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/file/MemoryFileIdGettable.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/file/FileInfoGettable.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/file/DefaultFileManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/file/FileManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/file/data/FileData.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/file/spi/FileIdGettable.java
  waldreg/service-layer/board/src/test/java/org/waldreg/board/file/FileManagerTest.java
Labels: size/L

#219 refactor : 파일을 여러개 저장가능하도록 수정
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/file/FileInfoGettable.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/file/DefaultFileManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/file/data/FileData.java
  waldreg/service-layer/board/src/test/java/org/waldreg/board/file/FileManagerTest.java
Labels: size/S

#220 feat : 파일 저장시 이미지, 파일 구분해서 가져오는 메소드 추가
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/file/FileInfoGettable.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/file/21bbe2a7-6598-4c5c-ad87-2214bc6d14a5.png
  waldreg/service-layer/board/src/main/java/org/waldreg/board/file/DefaultFileManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/file/a861301f-041a-463b-aaa7-d6831bae772d.png
  waldreg/service-layer/board/src/main/java/org/waldreg/board/file/data/FileData.java
  waldreg/service-layer/board/src/test/java/org/waldreg/board/file/FileManagerTest.java
Labels: size/M

#221 fix : image와 file을 구분하도록 수정함
  waldreg/service-layer/board/src/main/java/org/waldreg/board/file/DefaultFileManager.java
Labels: size/S

#222 fix : board 생성, 수정의 file 경로 저장, 삭제로직 수정
  waldreg/application-layer/board-controller/build.gradle
  waldreg/application-layer/board-controller/src/main/java/org/waldreg/controller/board/category/CategoryController.java
  waldreg/application-layer/board-controller/src/main/java/org/waldreg/controller/board/category/mapper/ControllerCategoryMapper.java
  waldreg/application-layer/board-controller/src/main/java/org/waldreg/controller/board/category/request/CategoryRequest.java
  waldreg/application-layer/board-controller/src/main/java/org/waldreg/controller/board/category/response/CategoryListResponse.java
  waldreg/application-layer/board-controller/src/main/java/org/waldreg/controller/board/category/response/CategoryResponse.java
  waldreg/application-layer/board-controller/src/main/java/org/waldreg/controller/board/response/memberTier/MemberTier.java
  waldreg/application-layer/board-controller/src/main/java/org/waldreg/controller/board/response/memberTier/MemberTierListResponse.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/exception/FutureCannotGetException.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/management/BoardManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/management/DefaultBoardManager.java
  waldreg/service-layer/board/src/test/java/org/waldreg/board/board/BoardManagerTest.java
Labels: size/L

#223 Board repository : Category Repository Test 작성
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/category/Category.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryBoardStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryCategoryStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/BoardMapper.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/MemoryBoardRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/category/BoardInCategoryMapper.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/category/CategoryMapper.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/category/MemoryCategoryRepository.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/board/BoardRepositoryTest.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/category/CategoryRepositoryTest.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/management/DefaultBoardManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/spi/BoardRepository.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/spi/CategoryExistChecker.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/spi/CategoryPerformer.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/category/spi/CategoryRepository.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/dto/CategoryDto.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/file/0bf126f8-9085-4f21-9a24-1ba6c33c33d5.png
  waldreg/service-layer/board/src/main/java/org/waldreg/board/file/aa9f2705-e3fe-4658-9ef6-97544bd33bfd.png
  waldreg/service-layer/board/src/test/java/org/waldreg/board/board/BoardManagerTest.java
Labels: size/L

#225 test : 댓글 생성 성공 레포지토리 테스트 작성
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/board/Board.java
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/board/comment/Comment.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryBoardStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryCategoryStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryCommentStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/BoardMapper.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/CommentInBoardMapper.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/MemoryBoardRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/comment/CommentMapper.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/comment/MemoryCommentRepository.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/board/BoardRepositoryTest.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/category/CategoryRepositoryTest.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/comment/CommentRepositoryTest.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/comment/management/DefaultCommentManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/comment/spi/CommentInBoardRepository.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/dto/BoardDto.java
Labels: size/L

#226 test : Comment Repository Test
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryCommentStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/BoardMapper.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/CommentInBoardMapper.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/comment/CommentMapper.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/comment/MemoryCommentRepository.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/comment/CommentRepositoryTest.java
Labels: test, size/L

#227 test : Board 삭제, 수정 시 Category Domain 의 BoardList에 반영되도록
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/category/Category.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryBoardStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryCommentStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/BoardMapper.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/CommentInBoardMapper.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/MemoryBoardRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/comment/CommentMapper.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/comment/MemoryCommentRepository.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/board/BoardRepositoryTest.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/management/DefaultBoardManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/spi/BoardInCategoryRepository.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/category/spi/CategoryRepository.java
  waldreg/service-layer/board/src/test/java/org/waldreg/board/board/BoardManagerTest.java
Labels: size/L

#228 test : board 삭제 시 board의 CommentList에 있던 댓글 모두 삭제 성공
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/MemoryBoardRepository.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/board/BoardRepositoryTest.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/category/CategoryRepositoryTest.java
Labels: test, size/M

#229 test : Category 삭제 시 Category의 BoardList에 있던 Board도 함께 삭제
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/category/MemoryCategoryRepository.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/category/CategoryRepositoryTest.java
Labels: size/M

#231 test : id로 유저 조회 성공 레포지토리 테스트
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/BoardMapper.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/UserInBoardMapper.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/boarduserinfo/MemoryBoardUserInfoRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/boarduserinfo/UserInfoMapper.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/board/BoardRepositoryTest.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/boarduserinfo/BoardUserInfoRepositoryTest.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/category/CategoryRepositoryTest.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/comment/CommentRepositoryTest.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/management/DefaultBoardManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/spi/BoardUserRepository.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/reaction/management/DefaultReactionManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/reaction/spi/ReactionUserRepository.java
  waldreg/service-layer/board/src/test/java/org/waldreg/board/board/BoardManagerTest.java
  waldreg/service-layer/board/src/test/java/org/waldreg/board/category/CategoryManagerTest.java
  waldreg/service-layer/board/src/test/java/org/waldreg/board/reaction/ReactionManagerTest.java
Labels: size/L

#232 test : userId로 user 조회 성공 레포지토리 테스트
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/boarduserinfo/MemoryBoardUserInfoRepository.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/boarduserinfo/BoardUserInfoRepositoryTest.java
Labels: test, size/M

#233 test : board에 reaction 추가 성공 레포지토리 테스트
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/board/reaction/Reaction.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/BoardMapper.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/MemoryBoardRepository.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/board/BoardRepositoryTest.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/board/ReactionInBoardRepositoryTest.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/dto/ReactionDto.java
  waldreg/service-layer/board/src/test/java/org/waldreg/board/reaction/ReactionManagerTest.java
Labels: test, size/L

#235 test : board의 reaction 조회 성공 레포지토리 테스트
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/board/reaction/Reaction.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/BoardMapper.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/MemoryBoardRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/boarduserinfo/MemoryBoardUserInfoRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/boarduserinfo/UserInfoMapper.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/board/ReactionInBoardRepositoryTest.java
Labels: test, size/M

#238 fix : 검색 로직 수정, 인수테스트 파일 삭제 수정
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/board/BoardAcceptanceTest.java
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/board/BoardAcceptanceTestHelper.java
  waldreg/application-layer/board-controller/src/main/java/org/waldreg/controller/board/board/BoardController.java
  waldreg/application-layer/board-controller/src/main/java/org/waldreg/controller/board/board/mapper/ControllerBoardMapper.java
  waldreg/application-layer/board-controller/src/main/java/org/waldreg/controller/board/board/response/BoardListResponse.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryBoardStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/MemoryBoardRepository.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/management/BoardManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/management/DefaultBoardManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/category/management/DefaultCategoryManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/comment/management/DefaultCommentManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/config/BoardPermissionConfigurer.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/file/DefaultFileManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/reaction/management/DefaultReactionManager.java
Labels: size/L

#243 test : 유저 가입 대기열 인수테스트 추가
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/user/UserAcceptanceTest.java
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/user/UserAcceptanceTestHelper.java
  waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/response/UserJoiningPoolListResponse.java
  waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/response/UserJoiningPoolResponse.java
Labels: size/XL

#244 test : 새로운 출석 면제 요청 테스트 추가
  waldreg/service-layer/attendance/build.gradle
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/exception/DoesNotRegisteredAttendanceException.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/exception/InvalidWaiverDateException.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/exception/TooFarDateException.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/rule/AttendanceRule.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/rule/valid/AttendanceDateValidator.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/waiver/DefaultWaiverManager.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/waiver/WaiverManager.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/waiver/dto/WaiverDto.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/waiver/spi/WaiverRepository.java
  waldreg/service-layer/attendance/src/test/java/org/waldreg/attendance/waiver/WaiverTest.java
  waldreg/settings.gradle
Labels: size/L

#245 feat : 출석 면제 요청 리스트 조회 테스트및 코드 추가
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/waiver/DefaultWaiverManager.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/waiver/WaiverManager.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/waiver/dto/WaiverDto.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/waiver/spi/WaiverRepository.java
  waldreg/service-layer/attendance/src/test/java/org/waldreg/attendance/waiver/WaiverTest.java
Labels: size/M

#247 feat : 출석 면제 승인 서비스 추가
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/exception/UnknownAttendanceTypeException.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/exception/UnknownUsersIdException.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/exception/UnknownWaiverIdException.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/AttendanceManager.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/DefaultAttendanceManager.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/dto/AttendanceTargetDto.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/spi/AttendanceRepository.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/spi/UserExistChecker.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/type/AttendanceType.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/waiver/DefaultWaiverManager.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/waiver/WaiverManager.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/waiver/dto/WaiverDto.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/waiver/spi/WaiverRepository.java
  waldreg/service-layer/attendance/src/test/java/org/waldreg/attendance/management/AttendanceTest.java
  waldreg/service-layer/attendance/src/test/java/org/waldreg/attendance/waiver/WaiverTest.java
Labels: size/L

#248 feat : 출석 상태를 강제로 변경하는 서비스 추가
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/exception/TooEarlyDateException.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/AttendanceManager.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/DefaultAttendanceManager.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/dto/AttendanceStatusChangeDto.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/dto/AttendanceTargetDto.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/spi/AttendanceRepository.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/rule/valid/AttendanceDateValidator.java
  waldreg/service-layer/attendance/src/test/java/org/waldreg/attendance/management/AttendanceTest.java
Labels: feature, test, size/L

#249 feat : 출석 대상 유저들의 출석 현황을 조회하는 테스트를 추가함
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/exception/InvalidDateException.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/AttendanceManager.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/DefaultAttendanceManager.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/dto/AttendanceDayDto.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/spi/AttendanceRepository.java
  waldreg/service-layer/attendance/src/test/java/org/waldreg/attendance/management/AttendanceTest.java
Labels: size/L

#246 feat : 유저 가입 대기열의 조회, 승인, 거절 기능추가
  waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/user/AdminUserConfigurer.java
  waldreg/application-layer/application-configurer/src/test/java/org/waldreg/config/user/AdminUserConfigurerTest.java
  waldreg/application-layer/board-controller/src/main/java/org/waldreg/controller/board/reaction/ReactionController.java
  waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/UserController.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/management/joiningpool/DefaultJoiningPoolManager.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/management/joiningpool/JoiningPoolManager.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/management/user/DefaultUserManager.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/management/user/UserManager.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/spi/JoiningPoolRepository.java
  waldreg/service-layer/user/src/test/java/org/waldreg/user/management/UserServiceTest.java
Labels: size/L

#250 feat : 자신의 출석 조회 서비스를 추가했습니다
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/AttendanceManager.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/DefaultAttendanceManager.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/dto/AttendanceUserDto.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/spi/AttendanceRepository.java
  waldreg/service-layer/attendance/src/test/java/org/waldreg/attendance/management/AttendanceTest.java
Labels: feature

#251 refactor : 유저에 관한 예외처리를 service-layer로 옮김
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryUserStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/user/MemoryUserRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/user/UserMapper.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/board/BoardRepositoryTest.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/board/ReactionInBoardRepositoryTest.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/boarduserinfo/BoardUserInfoRepositoryTest.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/category/CategoryRepositoryTest.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/comment/CommentRepositoryTest.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/user/UserRepositoryTest.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/dto/UserDto.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/management/joiningpool/DefaultJoiningPoolManager.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/management/user/DefaultUserManager.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/spi/CharacterRepository.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/spi/JoiningPoolRepository.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/spi/UserRepository.java
  waldreg/service-layer/user/src/test/java/org/waldreg/user/management/UserServiceTest.java
Labels: size/XL

#252 feat : 출석 체크 서비스를 추가함
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/exception/AlreadyAttendanceException.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/exception/DoesNotStartedAttendanceException.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/exception/WrongAttendanceIdentifyException.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/AttendanceManager.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/DefaultAttendanceManager.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/spi/AttendanceRepository.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/valid/AttendanceIdentifyValidable.java
  waldreg/service-layer/attendance/src/test/java/org/waldreg/attendance/management/AttendanceTest.java
Labels: feature, test, size/L

#253 feat : 가입 대기열 repository, storage 추가
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryJoiningPoolStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryUserStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/user/MemoryJoiningPoolRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/user/MemoryUserRepository.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/board/BoardRepositoryTest.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/board/ReactionInBoardRepositoryTest.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/boarduserinfo/BoardUserInfoRepositoryTest.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/category/CategoryRepositoryTest.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/comment/CommentRepositoryTest.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/user/JoiningPoolRepositoryTest.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/user/UserRepositoryTest.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/management/joiningpool/DefaultJoiningPoolManager.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/management/joiningpool/JoiningPoolManager.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/management/user/DefaultUserManager.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/management/user/UserManager.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/spi/JoiningPoolRepository.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/spi/UserRepository.java
  waldreg/service-layer/user/src/test/java/org/waldreg/user/management/UserServiceTest.java
Labels: size/XL

#254 test : TeamBuilding Acceptance Test
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/teambuilding/TeamBuildingAcceptanceTest.java
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/teambuilding/TeamBuildingAcceptanceTestHelper.java
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/user/UserAcceptanceTest.java
Labels: test, size/XXL

#258 feat : 출석관련 자동 상 벌점 부여 서비스 추가
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/schedule/AttendanceScheduler.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/schedule/dto/AttendanceUserStatusDto.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/schedule/spi/AttendanceScheduleRepository.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/schedule/spi/AttendanceScheduleRewardRepository.java
  waldreg/service-layer/attendance/src/test/java/org/waldreg/attendance/event/AttendanceEventTest.java
  waldreg/service-layer/attendance/src/test/java/org/waldreg/attendance/schedule/AttendanceSchedulerTest.java
Labels: feature, test, size/L

#259 feat : 출석 타입별 상,벌점 태그 연결 서비스 추가
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/attendance/Attendance.java
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/attendance/AttendancePerDate.java
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/attendance/AttendanceTypeReward.java
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/attendance/AttendanceUser.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/exception/UnknownAttendanceTypeException.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/exception/UnknownRewardTagIdException.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/AttendanceManager.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/DefaultAttendanceManager.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/spi/AttendanceRewardRepository.java
  waldreg/service-layer/attendance/src/test/java/org/waldreg/attendance/management/AttendanceTest.java
Labels: feature, test, size/L

#260 feat : 유저를 출석 대상에 등록 및 조회하는 서비스 추가
  waldreg/repository-layer/memory-repository/build.gradle
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryAttendanceStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/attendance/management/AttendanceManagementRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/attendance/management/mapper/AttendanceManagementMapper.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/attendance/management/AttendanceManagementRepositoryTest.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/type/AttendanceType.java
Labels: feature, test, size/L

#261 refactor : AttendanceManager의 confirm 메소드 분리
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryAttendanceStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/attendance/management/AttendanceManagementRepository.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/attendance/management/AttendanceManagementRepositoryTest.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/event/AttendanceEvent.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/AttendanceManager.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/DefaultAttendanceManager.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/spi/AttendanceRepository.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/valid/AttendanceIdentifyValidable.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/valid/AttendanceTargetValidable.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/valid/AttendanceValidator.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/valid/DefaultAttendanceValidator.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/valid/spi/AttendanceValidatorRepository.java
  waldreg/service-layer/attendance/src/test/java/org/waldreg/attendance/management/AttendanceTest.java
  waldreg/service-layer/attendance/src/test/java/org/waldreg/attendance/valid/DefaultAttendanceValidatorTest.java
Labels: feature, test, size/L

#262 refactor : AttendanceManager의 reward tag관련 메소드를 분리함
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/AttendanceManager.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/DefaultAttendanceManager.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/reward/AttendanceRewardManager.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/reward/DefaultAttendanceRewardManager.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/reward/spi/AttendanceRewardRepository.java
  waldreg/service-layer/attendance/src/test/java/org/waldreg/attendance/management/AttendanceTest.java
  waldreg/service-layer/attendance/src/test/java/org/waldreg/attendance/reward/AttendanceRewardManagerTest.java
Labels: refactor, test, size/L

#263 feat : 하루가 지날때마다 새로운 AttendanceCalendar를 생성하는 로직 추가
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/schedule/AttendanceScheduler.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/schedule/spi/AttendanceScheduleRepository.java
Labels: fix bug, feature, size/S

#265 feat : 해당하는 날의 달력이 비어있을때 추가하는 서비스 추가
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/attendance/Attendance.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryAttendanceStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/attendance/management/AttendanceManagementRepository.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/attendance/management/AttendanceManagementRepositoryTest.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/DefaultAttendanceManager.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/spi/AttendanceRepository.java
Labels: feature, size/M

#266 feat : 전체 출석대상 유저의 출석 현황 조회 서비스 추가
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/attendance/Attendance.java
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/attendance/AttendancePerDate.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryAttendanceStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/attendance/management/AttendanceManagementRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/attendance/management/mapper/AttendanceManagementMapper.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/attendance/management/AttendanceManagementRepositoryTest.java
Labels: feature, test, size/L

#267 feat : 특정 유저의 출석현황을 조회하는 서비스 추가
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryAttendanceStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/attendance/management/AttendanceManagementRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/attendance/management/mapper/AttendanceManagementMapper.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/attendance/management/AttendanceManagementRepositoryTest.java
Labels: feature, test, size/M

#268 feat : 지각 신청 도메인 추가
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/waiver/Waiver.java
Labels: feature, size/M

#269 feat : 공결 신청및 조회 서비스 추가
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/waiver/Waiver.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryAttendanceStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryWaiverStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/attendance/management/mapper/AttendanceManagementMapper.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/attendance/waiver/MemoryWaiverRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/attendance/waiver/mapper/MemoryWaiverMapper.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/attendance/waiver/MemoryWaiverRepositoryTest.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/waiver/DefaultWaiverManager.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/waiver/spi/WaiverRepository.java
Labels: size/L

#270 feat : 출석 면제 승인 성공 서비스 추가
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryAttendanceStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryWaiverStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/attendance/waiver/MemoryWaiverRepository.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/attendance/waiver/MemoryWaiverRepositoryTest.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/waiver/DefaultWaiverManager.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/waiver/spi/WaiverRepository.java
Labels: feature, test, size/M

#271 feat : Waiver 삭제 및 단일 조회 서비스 추가
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryWaiverStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/attendance/waiver/MemoryWaiverRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/attendance/waiver/mapper/MemoryWaiverMapper.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/attendance/waiver/MemoryWaiverRepositoryTest.java
Labels: feature, test, size/M

#274 feat : 일정 주기마다 유저 출석정보 조회 서비스 추가
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/attendance/AttendanceTypeReward.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryAttendanceStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/attendance/reward/MemoryAttendanceRewardRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/attendance/schedule/MemoryAttendanceScheduleRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/attendance/schedule/MemoryAttendanceScheduleRewardRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/attendance/schedule/mapper/MemoryAttendanceScheduleMapper.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/attendance/reward/MemoryAttendanceRewardRepositoryTest.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/attendance/schedule/MemoryAttendanceScheduleRepositoryTest.java
Labels: feature, test, size/XL

#276 feat : 특정 teamBuilding 조회 성공 서비스
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/management/DefaultTeamBuildingManager.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/management/TeamBuildingManager.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/spi/TeamBuildingRepository.java
  waldreg/service-layer/teambuilding/src/test/java/org/waldreg/teambuilding/TeamBuildingServiceTest.java
Labels: feature, size/M

#277 feat : 출석 관리 역할 등록
  waldreg/service-layer/attendance/build.gradle
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/config/AttendanceConfig.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/config/ScheduleConfig.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/schedule/AttendanceScheduler.java
Labels: fix bug, feature, size/M

#278 feat : 유저 출석대상 등록,삭제 컨트롤러 추가
  waldreg/application-layer/attendance-controller/build.gradle
  waldreg/application-layer/attendance-controller/src/main/java/org/waldreg/controller/attendance/exceptionadvice/AttendanceControllerAdvice.java
  waldreg/application-layer/attendance-controller/src/main/java/org/waldreg/controller/attendance/management/AttendanceController.java
  waldreg/application-layer/attendance-controller/src/main/java/org/waldreg/controller/attendance/management/mapper/AttendanceControllerMapper.java
  waldreg/application-layer/attendance-controller/src/main/java/org/waldreg/controller/attendance/management/response/AttendanceCheckResponse.java
  waldreg/settings.gradle
Labels: feature, size/L

#280 feat : 출석 면제 신청 컨트롤러 추가
  waldreg/application-layer/acceptance/build.gradle
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/attendance/AttendanceAcceptanceTest.java
  waldreg/application-layer/attendance-controller/src/main/java/org/waldreg/controller/attendance/exceptionadvice/AttendanceControllerAdvice.java
  waldreg/application-layer/attendance-controller/src/main/java/org/waldreg/controller/attendance/management/mapper/AttendanceControllerMapper.java
  waldreg/application-layer/attendance-controller/src/main/java/org/waldreg/controller/attendance/waiver/WaiverController.java
  waldreg/application-layer/attendance-controller/src/main/java/org/waldreg/controller/attendance/waiver/mapper/WaiverControllerMapper.java
  waldreg/application-layer/attendance-controller/src/main/java/org/waldreg/controller/attendance/waiver/request/AttendanceWaiverRequest.java
Labels: feature, size/L

#279 feat : 전체 팀빌딩 조회 성공 서비스
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/dto/TeamBuildingDto.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/management/DefaultTeamBuildingManager.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/management/TeamBuildingManager.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/spi/TeamBuildingRepository.java
  waldreg/service-layer/teambuilding/src/test/java/org/waldreg/teambuilding/TeamBuildingServiceTest.java
Labels: test, size/L

#264 feat : token 을 이용한 soket 용 임시 토큰 발행기능 추가
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/authentication/AuthenticationAcceptanceTest.java
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/authentication/AuthenticationAcceptanceTestHelper.java
  waldreg/application-layer/auth-controller/build.gradle
  waldreg/application-layer/auth-controller/src/main/java/org/waldreg/auth/AuthController.java
  waldreg/application-layer/auth-controller/src/main/java/org/waldreg/auth/response/TemporaryTokenResponse.java
Labels: size/L

#282 feat : 팀빌딩 수정(팀빌딩 제목 수정) 성공 서비스
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/dto/TeamBuildingDto.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/management/DefaultTeamBuildingManager.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/management/TeamBuildingManager.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/spi/TeamBuildingRepository.java
  waldreg/service-layer/teambuilding/src/test/java/org/waldreg/teambuilding/TeamBuildingServiceTest.java
Labels: feature, size/M

#283 feat : 팀빌딩 삭제 성공 서비스
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/management/DefaultTeamBuildingManager.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/management/TeamBuildingManager.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/spi/TeamBuildingRepository.java
  waldreg/service-layer/teambuilding/src/test/java/org/waldreg/teambuilding/TeamBuildingServiceTest.java
Labels: feature, size/S

#281 feat : 출석 컨트롤러 완성
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/attendance/AttendanceAcceptanceTest.java
  waldreg/application-layer/attendance-controller/src/main/java/org/waldreg/controller/attendance/exceptionadvice/AttendanceControllerAdvice.java
  waldreg/application-layer/attendance-controller/src/main/java/org/waldreg/controller/attendance/management/AttendanceController.java
  waldreg/application-layer/attendance-controller/src/main/java/org/waldreg/controller/attendance/management/mapper/AttendanceControllerMapper.java
  waldreg/application-layer/attendance-controller/src/main/java/org/waldreg/controller/attendance/management/request/AttendanceModifyRequest.java
  waldreg/application-layer/attendance-controller/src/main/java/org/waldreg/controller/attendance/management/response/AttendancePerDayResponse.java
  waldreg/application-layer/attendance-controller/src/main/java/org/waldreg/controller/attendance/management/response/AttendanceUserResponse.java
  waldreg/application-layer/attendance-controller/src/main/java/org/waldreg/controller/attendance/reward/AttendanceRewardController.java
  waldreg/application-layer/attendance-controller/src/main/java/org/waldreg/controller/attendance/valid/AttendanceValidController.java
  waldreg/application-layer/attendance-controller/src/main/java/org/waldreg/controller/attendance/valid/request/AttendanceIdentifyRequest.java
  waldreg/application-layer/attendance-controller/src/main/java/org/waldreg/controller/attendance/waiver/WaiverController.java
  waldreg/application-layer/attendance-controller/src/main/java/org/waldreg/controller/attendance/waiver/mapper/WaiverControllerMapper.java
  waldreg/application-layer/attendance-controller/src/main/java/org/waldreg/controller/attendance/waiver/response/AttendanceWaiverResponse.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/type/AttendanceType.java
Labels: size/XL

#284 fix : UserExistChecker 등록
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/attendance/management/AttendanceUserExistChecker.java
Labels: fix bug, feature, size/S

#285 feat : 새로운 팀빌딩 생성 서비스 예외 처리
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/exception/InvalidDateFormatException.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/exception/ContentOverflowException.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/exception/InvalidTeamCountException.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/exception/InvalidUserWeightException.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/management/DefaultTeamBuildingManager.java
  waldreg/service-layer/teambuilding/src/test/java/org/waldreg/teambuilding/TeamBuildingServiceTest.java
Labels: feature, test, size/L

#286 feat : 특정 팀빌딩 그룹 조회 서비스 예외 처리
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/dto/TeamBuildingDto.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/exception/UnknownTeamBuildingIdException.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/management/DefaultTeamBuildingManager.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/management/TeamBuildingManager.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/spi/TeamBuildingRepository.java
  waldreg/service-layer/teambuilding/src/test/java/org/waldreg/teambuilding/TeamBuildingServiceTest.java
Labels: feature, test, size/M

#288 feat : 팀빌딩 전체 조회 서비스 예외처리
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/exception/InvalidRangeException.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/management/DefaultTeamBuildingManager.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/management/PerPage.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/spi/TeamBuildingRepository.java
  waldreg/service-layer/teambuilding/src/test/java/org/waldreg/teambuilding/TeamBuildingServiceTest.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/management/user/DefaultUserManager.java
Labels: feature, test, size/M

#290 feat : 팀빌딩 수정 서비스 예외처리
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/management/DefaultTeamBuildingManager.java
  waldreg/service-layer/teambuilding/src/test/java/org/waldreg/teambuilding/TeamBuildingServiceTest.java
Labels: feature, size/M

#291 feat : 팀빌딩 삭제 서비스 예외처리
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/management/DefaultTeamBuildingManager.java
  waldreg/service-layer/teambuilding/src/test/java/org/waldreg/teambuilding/TeamBuildingServiceTest.java
Labels: feature, test, size/S

#292 test : 팀빌딩 그룹 생성 때 존재하지 않는 유저로 생성 시도 시 실패
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/exception/UnknownUserIdException.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/management/DefaultTeamBuildingManager.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/spi/TeamBuildingUserRepository.java
  waldreg/service-layer/teambuilding/src/test/java/org/waldreg/teambuilding/TeamBuildingServiceTest.java
Labels: test, size/M

#295 feat : 팀빌딩 그룹 내 팀이름 변경 성공 서비스
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/teambuilding/TeamBuildingAcceptanceTest.java
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/teambuilding/TeamBuildingAcceptanceTestHelper.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/team/management/DefaultTeamManager.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/team/management/TeamManager.java
  waldreg/service-layer/teambuilding/src/test/java/org/waldreg/team/TeamServiceTest.java
Labels: feature, size/L

#296 feat : 팀빌딩 그룹 내 팀 삭제 성공 서비스
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/team/management/DefaultTeamManager.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/team/management/TeamManager.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/team/spi/TeamRepository.java
  waldreg/service-layer/teambuilding/src/test/java/org/waldreg/team/TeamServiceTest.java
Labels: size/S

#298 feat : 새로운 팀 추가 서비스 예외 처리
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/exception/ContentOverflowException.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/exception/DuplicateUserSelectException.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/exception/DuplicatedTeamNameException.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/exception/InvalidRangeException.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/exception/InvalidTeamCountException.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/exception/InvalidUserWeightException.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/exception/UnknownTeamBuildingIdException.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/exception/UnknownUserIdException.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/team/dto/TeamDto.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/team/management/DefaultTeamManager.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/team/spi/TeamRepository.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/team/spi/TeamUserRepository.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/management/DefaultTeamBuildingManager.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/management/teamcreator/TeamCreator.java
  waldreg/service-layer/teambuilding/src/test/java/org/waldreg/team/TeamServiceTest.java
  waldreg/service-layer/teambuilding/src/test/java/org/waldreg/teambuilding/TeamBuildingServiceTest.java
Labels: feature, test, size/L

#297 feat : Socket Context Holder 추가
  waldreg/core-layer/socket/src/main/java/org/waldreg/core/socket/holder/SocketContenxtCascadable.java
  waldreg/core-layer/socket/src/main/java/org/waldreg/core/socket/holder/SocketContextGettable.java
  waldreg/core-layer/socket/src/main/java/org/waldreg/core/socket/holder/SocketContextHolder.java
  waldreg/core-layer/socket/src/main/java/org/waldreg/core/socket/sessionstage/SessionStage.java
  waldreg/core-layer/socket/src/main/java/org/waldreg/core/socket/sessionstage/SessionStageGettable.java
  waldreg/core-layer/socket/src/main/java/org/waldreg/core/socket/sessionstage/SessionStageHoldable.java
  waldreg/settings.gradle
Labels: size/M

#300 feat : update specific team Service Exception
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/exception/InvalidUserWeightException.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/exception/UnknownTeamIdException.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/team/management/DefaultTeamManager.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/team/spi/TeamRepository.java
  waldreg/service-layer/teambuilding/src/test/java/org/waldreg/team/TeamServiceTest.java
Labels: feature, test, size/L

#302 feat : 팀빌딩 그룹 내 팀이름 변경 서비스 예외 처리
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/team/management/DefaultTeamManager.java
  waldreg/service-layer/teambuilding/src/test/java/org/waldreg/team/TeamServiceTest.java
Labels: feature, test, size/L

#306 test : 팀빌딩 생성 성공 레포지토리 테스트
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/teambuilding/TeamBuilding.java
  waldreg/repository-layer/memory-repository/build.gradle
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryTeamBuildingStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/teambuilding/MemoryTeamBuildingRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/teambuilding/TeamBuildingMapper.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/teambuilding/TeamBuildingRepositoryTest.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/team/spi/TeamRepository.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/dto/TeamBuildingDto.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/dto/TeamDto.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/management/DefaultTeamBuildingManager.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/spi/TeamBuildingRepository.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/spi/TeamBuildingsTeamRepository.java
  waldreg/service-layer/teambuilding/src/test/java/org/waldreg/teambuilding/TeamBuildingServiceTest.java
Labels: test

#305 refactor : 검증관련 로직을 repository -> service layer로 옮김
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/permission/PermissionAcceptanceTest.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/character/MemoryCharacterRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/character/MemoryUserExistChecker.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/character/CharacterRepositoryTest.java
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/exception/UnknownUsersIdException.java
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/management/DefaultCharacterManager.java
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/spi/CharacterRepository.java
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/spi/UserExistChecker.java
  waldreg/stable-service-layer/character/src/test/java/org/waldreg/character/management/DefaultCharacterManagerTest.java
Labels: refactor, test

#307 feat : 생성된 팀 빌딩에 팀 목록 업데이트 레포지토리 테스트
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryTeamBuildingStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryTeamStorage.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/teambuilding/TeamBuildingRepositoryTest.java
Labels: test, size/M

#308 test : teamBuilding_id로 특정 팀빌딩 조회 레포지토리 테스트
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryTeamBuildingStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/teambuilding/MemoryTeamBuildingRepository.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/teambuilding/TeamBuildingRepositoryTest.java
Labels: test, size/M

#309 test : 전체 teamBuilding 조회 레포지토리 성공 테스트
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/teambuilding/TeamBuilding.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryTeamBuildingStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/teambuilding/MemoryTeamBuildingRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/teambuilding/TeamBuildingMapper.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/teambuilding/TeamBuildingRepositoryTest.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/management/DefaultTeamBuildingManager.java
Labels: test, size/L

#301 feat : 게시글 응답에 댓글개수, 조회수 추가
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/board/BoardAcceptanceTest.java
  waldreg/application-layer/board-controller/src/main/java/org/waldreg/controller/board/board/mapper/ControllerBoardMapper.java
  waldreg/application-layer/board-controller/src/main/java/org/waldreg/controller/board/board/response/BoardResponse.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/MemoryBoardRepository.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/management/DefaultBoardManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/spi/BoardInCommentRepository.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/comment/spi/CommentRepository.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/dto/BoardDto.java
  waldreg/service-layer/board/src/test/java/org/waldreg/board/board/BoardManagerTest.java
Labels: size/M

#310 test : 팀빌딩 제목 수정 성공 레포지토리 테스트
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/teambuilding/MemoryTeamBuildingRepository.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/teambuilding/TeamBuildingRepositoryTest.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/management/DefaultTeamBuildingManager.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/spi/TeamBuildingRepository.java
Labels: test, size/M

#311 test : 팀빌딩 id로 팀빌딩 삭제 성공 레포지토리 테스트
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryTeamBuildingStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/teambuilding/MemoryTeamBuildingRepository.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/teambuilding/TeamBuildingRepositoryTest.java
Labels: test, size/M

#313 test : team_id로 team 조회 레포지토리 테스트
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryTeamStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/team/MemoryTeamRepository.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/team/TeamRepositoryTest.java
Labels: test

#314 test : 팀 정보 수정 레포지토리 테스트
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryTeamStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/team/MemoryTeamRepository.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/team/TeamRepositoryTest.java
Labels: test, size/M

#315 test : team_id로 team 삭제 레포지토리 테스트
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryTeamStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/team/MemoryTeamRepository.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/team/TeamRepositoryTest.java
Labels: test, size/S

#316 test : teambuildingId로 team 전체 목록, user 전체 목록 조회 레포지토리
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryTeamStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/team/MemoryTeamRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/team/TeamMapper.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/teambuilding/TeamBuildingMapper.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/teambuilding/TeamInTeamBuildingMapper.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/team/TeamRepositoryTest.java
Labels: test, size/L

#317 feat : teamBuildingRepo, teamRepo의 변경 사항이 서로 반영 될 수 있게
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryBoardStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/team/MemoryTeamRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/team/TeamMapper.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/teambuilding/MemoryTeamBuildingRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/teambuilding/TeamBuildingMapper.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/teambuilding/TeamInTeamBuildingMapper.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/teambuilding/TeamBuildingRepositoryTest.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/comment/management/DefaultCommentManager.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/team/management/DefaultTeamManager.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/teambuilding/management/DefaultTeamBuildingManager.java
  waldreg/service-layer/teambuilding/src/test/java/org/waldreg/teambuilding/TeamBuildingServiceTest.java
Labels: test, size/L

#320 feat : TeamBuildingControllerAdvice 추가
  waldreg/application-layer/teambuilding-controller/src/main/java/org/waldreg/controller/teambuilding/exceptionadvice/TeamBuildingControllerAdvice.java
Labels: test, size/L

#322 feat : PostMappingController 추가 : 팀 추가
  waldreg/application-layer/teambuilding-controller/src/main/java/org/waldreg/controller/teambuilding/TeamBuildingController.java
  waldreg/application-layer/teambuilding-controller/src/main/java/org/waldreg/controller/teambuilding/mapper/ControllerTeamBuildingMapper.java
Labels: feature, size/S

#323 feat : GetMappingController 추가 : 특정 팀빌딩 조회
  waldreg/application-layer/teambuilding-controller/src/main/java/org/waldreg/controller/teambuilding/TeamBuildingController.java
  waldreg/application-layer/teambuilding-controller/src/main/java/org/waldreg/controller/teambuilding/mapper/ControllerTeamBuildingMapper.java
  waldreg/application-layer/teambuilding-controller/src/main/java/org/waldreg/controller/teambuilding/response/TeamResponse.java
  waldreg/application-layer/teambuilding-controller/src/main/java/org/waldreg/controller/teambuilding/response/UserResponse.java
Labels: feature

#324 feat : teambuilding Controller
  waldreg/application-layer/teambuilding-controller/src/main/java/org/waldreg/controller/teambuilding/TeamBuildingController.java
  waldreg/application-layer/teambuilding-controller/src/main/java/org/waldreg/controller/teambuilding/mapper/ControllerTeamBuildingMapper.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/teambuildinguserinfo/MemoryTeamBuildingUserInfoRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/teambuildinguserinfo/TeamBuildingUserInfoMapper.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/team/TeamRepositoryTest.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/teambuilding/TeamBuildingRepositoryTest.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/teambuildinguserinfo/TeamBuildingUserInfoRepositoryTest.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/teambuilding/management/DefaultTeamBuildingManager.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/teambuilding/management/TeamBuildingManager.java
Labels: feature, size/L

#325 test : teambuilding acceptance test
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/teambuilding/TeamBuildingAcceptanceTest.java
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/teambuilding/TeamBuildingAcceptanceTestHelper.java
  waldreg/application-layer/attendance-controller/src/main/java/org/waldreg/controller/attendance/socket/AttendanceSocketController.java
  waldreg/application-layer/attendance-controller/src/main/java/org/waldreg/controller/attendance/socket/lock/Lock.java
  waldreg/application-layer/teambuilding-controller/src/main/java/org/waldreg/controller/teambuilding/TeamBuildingController.java
  waldreg/application-layer/teambuilding-controller/src/main/java/org/waldreg/controller/teambuilding/exceptionadvice/TeamBuildingControllerAdvice.java
  waldreg/application-layer/teambuilding-controller/src/main/java/org/waldreg/controller/teambuilding/mapper/ControllerTeamBuildingMapper.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/character/MemoryCharacterRepository.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/character/CharacterRepositoryTest.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/team/management/DefaultTeamManager.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/management/joiningpool/DefaultJoiningPoolManager.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/management/user/DefaultUserManager.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/spi/UsersCharacterRepository.java
  waldreg/service-layer/user/src/test/java/org/waldreg/user/management/UserServiceTest.java
Labels: test, size/L

#334 feat : character-jpa repository 패키지 작성
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/calendar/Schedule.java
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/character/Character.java
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/character/Permission.java
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/user/User.java
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/user/UserInfo.java
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/user/UserJoiningPool.java
  waldreg/repository-layer/character-jpa/build.gradle
  waldreg/repository-layer/character-jpa/src/main/java/org/waldreg/repository/character/repository/JpaCharacterRepository.java
  waldreg/repository-layer/character-jpa/src/main/java/org/waldreg/repository/character/repository/JpaPermissionRepository.java
  waldreg/repository-layer/character-jpa/src/main/java/org/waldreg/repository/character/repository/JpaUserRepository.java
  waldreg/repository-layer/character-jpa/src/test/java/org/waldreg/repository/character/JpaCharacterTestInitializer.java
  waldreg/repository-layer/character-jpa/src/test/java/org/waldreg/repository/character/repository/JpaCharacterRepositoryTest.java
  waldreg/repository-layer/character-jpa/src/test/resources/h2-application.properties
  waldreg/settings.gradle
Labels: size/L

#336 fix : repository 마이그레이션 세팅
  waldreg/application-layer/acceptance/build.gradle
  waldreg/application-layer/acceptance/src/main/resources/application.properties
  waldreg/application-layer/acceptance/src/test/resources/application.properties
  waldreg/application-layer/application-configurer/build.gradle
  waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/character/AdminCharacterConfigurer.java
  waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/character/GuestCharacterConfigurer.java
  waldreg/application-layer/character-controller/build.gradle
  waldreg/repository-layer/memory-repository/build.gradle
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryAttendanceStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryBoardStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryCategoryStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryCharacterStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryCommentStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryJoiningPoolStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryRewardTagStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryScheduleStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryTeamBuildingStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryTeamStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryUserStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryWaiverStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/attendance/management/AttendanceManagementRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/attendance/management/AttendanceUserExistChecker.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/attendance/management/mapper/AttendanceManagementMapper.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/attendance/reward/MemoryAttendanceRewardRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/attendance/schedule/MemoryAttendanceScheduleRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/attendance/schedule/MemoryAttendanceScheduleRewardRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/attendance/schedule/mapper/MemoryAttendanceScheduleMapper.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/attendance/valid/MemoryAttendanceValidatorRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/attendance/waiver/MemoryWaiverRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/attendance/waiver/mapper/MemoryWaiverMapper.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/auth/MemoryAuthRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/BoardMapper.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/CommentInBoardMapper.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/MemoryBoardRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/board/UserInBoardMapper.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/boarduserinfo/MemoryBoardUserInfoRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/boarduserinfo/UserInfoMapper.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/category/BoardInCategoryMapper.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/category/CategoryMapper.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/category/MemoryCategoryRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/character/MemoryCharacterRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/comment/MemoryCommentRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/reward/MemoryRewardTagRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/reward/RewardTagMapper.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/schedule/MemoryScheduleRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/schedule/ScheduleMapper.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/team/MemoryTeamRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/team/TeamMapper.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/teambuilding/MemoryTeamBuildingRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/teambuilding/TeamInTeamBuildingMapper.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/teambuildinguserinfo/MemoryTeamBuildingUserInfoRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/user/MemoryJoiningPoolRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/user/MemoryUserRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/usersreward/MemoryUsersRewardRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/usersreward/UsersRewardMapper.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/config/UserPermissionConfigurer.java
Labels: size/XXL

#340 feat : JpaRewardTagRepository 완성
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/rewardtag/RewardTag.java
  waldreg/repository-layer/reward-jpa/src/main/java/org/waldreg/repository/reward/repository/JpaRewardTagRepository.java
  waldreg/repository-layer/reward-jpa/src/test/java/org/waldreg/repository/reward/JpaRewardTestInitializer.java
  waldreg/repository-layer/reward-jpa/src/test/java/org/waldreg/repository/reward/repository/JpaRewardTagRepositoryTest.java
  waldreg/repository-layer/reward-jpa/src/test/resources/h2-application.properties
  waldreg/settings.gradle
Labels: feature, test, size/L

#341 feat : JpaRewardTagWrapperRepository 완성
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/user/User.java
  waldreg/repository-layer/reward-jpa/src/main/java/org/waldreg/repository/reward/repository/JpaRewardTagWrapperRepository.java
  waldreg/repository-layer/reward-jpa/src/main/java/org/waldreg/repository/reward/repository/JpaRewardUserRepository.java
  waldreg/repository-layer/reward-jpa/src/test/java/org/waldreg/repository/reward/repository/JpaRewardTagRepositoryTest.java
  waldreg/repository-layer/reward-jpa/src/test/java/org/waldreg/repository/reward/repository/JpaRewardUserRepositoryTest.java
  waldreg/repository-layer/reward-jpa/src/test/java/org/waldreg/repository/reward/repository/TestJpaCharacterRepository.java
Labels: size/L

#345 fix : User Controller build.gradle
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/user/UserAcceptanceTest.java
  waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/user/AdminUserConfigurer.java
  waldreg/application-layer/application-configurer/src/test/java/org/waldreg/config/user/AdminUserConfigurerTest.java
  waldreg/application-layer/user-controller/build.gradle
  waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/mapper/ControllerUserMapper.java
  waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/response/UserResponse.java
Labels: test, size/M

#346 feat : Reward 서비스 저장소 memory -> DB로 이전 완료
  waldreg/application-layer/reward-controller/build.gradle
  waldreg/repository-layer/reward-jpa/src/main/java/org/waldreg/repository/reward/exist/UserExistCheckerServiceProvider.java
  waldreg/repository-layer/reward-jpa/src/main/java/org/waldreg/repository/reward/user/UsersRewardRepositoryServiceProvider.java
  waldreg/repository-layer/reward-jpa/src/main/java/org/waldreg/repository/reward/user/mapper/RewardTagWrapperMapper.java
  waldreg/repository-layer/reward-jpa/src/test/java/org/waldreg/repository/reward/user/RewardTagRepositoryServiceProviderTest.java
Labels: size/L

#347 feat : JpaAttendanceRepository 작성
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/attendance/Attendance.java
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/attendance/AttendanceTypeReward.java
  waldreg/repository-layer/attendance-jpa/build.gradle
  waldreg/repository-layer/attendance-jpa/src/main/java/org/waldreg/repository/attendance/repository/JpaAttendanceRepository.java
  waldreg/repository-layer/attendance-jpa/src/main/java/org/waldreg/repository/attendance/repository/JpaAttendanceTypeRewardRepository.java
  waldreg/repository-layer/attendance-jpa/src/main/java/org/waldreg/repository/attendance/repository/JpaAttendanceUserRepository.java
  waldreg/repository-layer/attendance-jpa/src/main/java/org/waldreg/repository/attendance/repository/JpaRewardTagRepository.java
  waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/JpaAttendanceTestInitializer.java
  waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/repository/JpaAttendanceRepositoryTest.java
  waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/repository/TestJpaCharacterRepository.java
  waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/repository/TestJpaUserRepository.java
  waldreg/repository-layer/attendance-jpa/src/test/resources/h2-application.properties
  waldreg/settings.gradle
Labels: size/L

#348 test : JpaScheduleRepository 구현 및 테스트
  waldreg/repository-layer/schedule-jpa/build.gradle
  waldreg/repository-layer/schedule-jpa/src/main/java/org/waldreg/repository/schedule/repository/JpaScheduleRepository.java
  waldreg/repository-layer/schedule-jpa/src/test/java/org/waldreg/repository/schedule/JpaScheduleTestInitializer.java
  waldreg/repository-layer/schedule-jpa/src/test/java/org/waldreg/repository/schedule/repository/JpaScheduleRepositoryTest.java
  waldreg/repository-layer/schedule-jpa/src/test/resources/h2-application.properties
  waldreg/repository-layer/user-jpa/src/test/java/org/waldreg/repository/user/repository/JpaUserRepositoryTest.java
  waldreg/settings.gradle
Labels: test, size/L

#342 feat : jpa repository & test 작성 완료
  waldreg/application-layer/board-controller/src/main/java/org/waldreg/controller/board/category/mapper/ControllerCategoryMapper.java
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/board/comment/Comment.java
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/board/reaction/Reaction.java
  waldreg/repository-layer/board-jpa/build.gradle
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/BoardRepositoryServiceProvider.java
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/CategoryRepositoryServiceProvider.java
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/mapper/BoardRepositoryMapper.java
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/mapper/BoardUserRepositoryMapper.java
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/mapper/CategoryRepositoryMapper.java
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/mapper/CommentRepositoryMapper.java
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/repository/JpaBoardRepository.java
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/repository/JpaCategoryRepository.java
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/repository/JpaCharacterRepository.java
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/repository/JpaCommentRepository.java
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/repository/JpaReactionRepository.java
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/repository/JpaReactionUserRepository.java
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/repository/JpaUserRepository.java
  waldreg/repository-layer/board-jpa/src/test/java/org/waldreg/repository/board/BoardRepositoryTest.java
  waldreg/repository-layer/board-jpa/src/test/java/org/waldreg/repository/board/CategoryRepositoryTest.java
  waldreg/repository-layer/board-jpa/src/test/java/org/waldreg/repository/board/JpaBoardTestInitializer.java
  waldreg/repository-layer/board-jpa/src/test/java/org/waldreg/repository/board/repository/JpaBoardRepositoryTest.java
  waldreg/repository-layer/board-jpa/src/test/java/org/waldreg/repository/board/repository/JpaCategoryRepositoryTest.java
  waldreg/repository-layer/board-jpa/src/test/java/org/waldreg/repository/board/repository/JpaCommentRepositoryTest.java
  waldreg/repository-layer/board-jpa/src/test/java/org/waldreg/repository/board/repository/JpaReactionRepositoryTest.java
  waldreg/repository-layer/board-jpa/src/test/resources/h2-application.properties
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/management/DefaultBoardManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/spi/BoardInCategoryRepository.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/dto/CategoryDto.java
  waldreg/settings.gradle
Labels: size/XXL

#339 fix : board controller 의 카테고리별 전체조회 url을 수정
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/board/BoardAcceptanceTestHelper.java
  waldreg/application-layer/board-controller/src/main/java/org/waldreg/controller/board/board/BoardController.java
Labels: size/XS

#350 test : ScheduleRepositoryServiceProvider 구현 및 테스트
  waldreg/application-layer/schedule-controller/build.gradle
  waldreg/repository-layer/schedule-jpa/src/main/java/org/waldreg/repository/schedule/ScheduleRepositoryServiceProvider.java
  waldreg/repository-layer/schedule-jpa/src/main/java/org/waldreg/repository/schedule/mapper/ScheduleRepositoryMapper.java
  waldreg/repository-layer/schedule-jpa/src/test/java/org/waldreg/repository/schedule/ScheduleRepositoryTest.java
Labels: test, size/L

#349 feat : JpaWaiverRepository 작성
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/waiver/Waiver.java
  waldreg/repository-layer/attendance-jpa/src/main/java/org/waldreg/repository/attendance/waiver/repository/JpaUserRepository.java
  waldreg/repository-layer/attendance-jpa/src/main/java/org/waldreg/repository/attendance/waiver/repository/JpaWaiverRepository.java
  waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/helper/TestJpaCharacterRepository.java
  waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/helper/TestJpaUserRepository.java
  waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/repository/JpaAttendanceRepositoryTest.java
  waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/waiver/JpaWaiverRepositoryTest.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/waiver/spi/WaiverRepository.java
Labels: size/L

#352 feat : MemoryWaiverRepository -> JpaWaiverRepository
  waldreg/repository-layer/attendance-jpa/src/main/java/org/waldreg/repository/attendance/repository/JpaAttendanceUserRepository.java
  waldreg/repository-layer/attendance-jpa/src/main/java/org/waldreg/repository/attendance/schedule/AttendanceScheduleRepositoryServiceProvider.java
  waldreg/repository-layer/attendance-jpa/src/main/java/org/waldreg/repository/attendance/schedule/AttendanceScheduleRewardRepositoryServiceProvider.java
  waldreg/repository-layer/attendance-jpa/src/main/java/org/waldreg/repository/attendance/schedule/mapper/ScheduleMapper.java
  waldreg/repository-layer/attendance-jpa/src/main/java/org/waldreg/repository/attendance/waiver/WaiverRepositoryServiceProvider.java
  waldreg/repository-layer/attendance-jpa/src/main/java/org/waldreg/repository/attendance/waiver/mapper/WaiverMapper.java
  waldreg/repository-layer/attendance-jpa/src/main/java/org/waldreg/repository/attendance/waiver/repository/JpaWaiverUserRepository.java
  waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/JpaAttendanceTestInitializer.java
  waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/repository/JpaAttendanceRepositoryTest.java
  waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/schedule/AttendanceScheduleRepositoryServiceProviderTest.java
  waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/schedule/AttendanceScheduleRewardRepositoryServiceProviderTest.java
  waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/waiver/JpaWaiverServiceProviderTest.java
  waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/waiver/repository/JpaWaiverRepositoryTest.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/management/DefaultAttendanceManager.java
Labels: size/XL

#351 feat : board repository 작성완료 + comment Repository 작성완료
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/board/comment/Comment.java
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/BoardRepositoryServiceProvider.java
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/CategoryRepositoryServiceProvider.java
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/CommentRepositoryServiceProvider.java
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/mapper/BoardRepositoryMapper.java
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/mapper/BoardUserRepositoryMapper.java
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/mapper/CategoryRepositoryMapper.java
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/mapper/CommentRepositoryMapper.java
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/repository/JpaCommentRepository.java
  waldreg/repository-layer/board-jpa/src/test/java/org/waldreg/repository/board/BoardRepositoryTest.java
  waldreg/repository-layer/board-jpa/src/test/java/org/waldreg/repository/board/CommentRepositoryTest.java
  waldreg/repository-layer/board-jpa/src/test/java/org/waldreg/repository/board/repository/JpaCommentRepositoryTest.java
Labels: size/XXL

#354 feat : MemoryAttendanceRewardRepository -> Jpa...Repository
  waldreg/application-layer/attendance-controller/build.gradle
  waldreg/repository-layer/attendance-jpa/src/main/java/org/waldreg/repository/attendance/management/AttendanceRepositoryServiceProvider.java
  waldreg/repository-layer/attendance-jpa/src/main/java/org/waldreg/repository/attendance/management/UserExistCheckerServiceProvider.java
  waldreg/repository-layer/attendance-jpa/src/main/java/org/waldreg/repository/attendance/management/mapper/AttendanceManagementMapper.java
  waldreg/repository-layer/attendance-jpa/src/main/java/org/waldreg/repository/attendance/repository/JpaAttendanceUserRepository.java
  waldreg/repository-layer/attendance-jpa/src/main/java/org/waldreg/repository/attendance/repository/JpaUserRepository.java
  waldreg/repository-layer/attendance-jpa/src/main/java/org/waldreg/repository/attendance/reward/AttendanceRewardRepositoryServiceProvider.java
  waldreg/repository-layer/attendance-jpa/src/main/java/org/waldreg/repository/attendance/reward/repository/JpaAttendanceRewardTagRepository.java
  waldreg/repository-layer/attendance-jpa/src/main/java/org/waldreg/repository/attendance/waiver/WaiverRepositoryServiceProvider.java
  waldreg/repository-layer/attendance-jpa/src/main/java/org/waldreg/repository/attendance/waiver/repository/JpaWaiverUserRepository.java
  waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/helper/TestJpaUserRepository.java
  waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/management/AttendanceRepositoryServiceProviderTest.java
  waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/repository/JpaAttendanceRepositoryTest.java
  waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/reward/AttendanceRewardRepositoryServiceProviderTest.java
  waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/reward/TestJpaRewardTagRepository.java
  waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/schedule/AttendanceScheduleRepositoryServiceProviderTest.java
  waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/schedule/AttendanceScheduleRewardRepositoryServiceProviderTest.java
  waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/valid/AttendanceValidatorRepositoryServiceProviderTest.java
  waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/waiver/JpaWaiverServiceProviderTest.java
  waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/waiver/repository/JpaWaiverRepositoryTest.java
Labels: size/XL

#355 fix : character_name의 길이가 25를 넘어가지 않도록 수정
  waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/CharacterController.java
  waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/request/CharacterRequest.java
Labels: size/XS

#358 test : TeamBuildingRepository test, TeamBuildingRepositoryMapper
  waldreg/repository-layer/teambuilding-jpa/src/main/java/org/waldreg/repository/teambuilding/TeamBuildingRepositoryServiceProvider.java
  waldreg/repository-layer/teambuilding-jpa/src/main/java/org/waldreg/repository/teambuilding/mapper/TeamBuildingRepositoryMapper.java
  waldreg/repository-layer/teambuilding-jpa/src/main/java/org/waldreg/repository/teambuilding/repository/JpaTeamBuildingRepository.java
  waldreg/repository-layer/teambuilding-jpa/src/test/java/org/waldreg/repository/teambuilding/TeamBuildingRepositoryTest.java
  waldreg/repository-layer/teambuilding-jpa/src/test/java/org/waldreg/repository/teambuilding/repository/JpaTeamBuildingRepositoryTest.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/teambuilding/dto/TeamBuildingDto.java
  waldreg/service-layer/teambuilding/src/main/java/org/waldreg/teambuilding/teambuilding/management/DefaultTeamBuildingManager.java
  waldreg/service-layer/user/src/test/java/org/waldreg/user/management/UserServiceTest.java
Labels: test, size/XL

#360 test : JpaTeamRepositoryTest
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/teambuilding/TeamBuilding.java
  waldreg/repository-layer/teambuilding-jpa/src/main/java/org/waldreg/repository/teambuilding/TeamBuildingRepositoryServiceProvider.java
  waldreg/repository-layer/teambuilding-jpa/src/main/java/org/waldreg/repository/teambuilding/repository/JpaTeamRepository.java
  waldreg/repository-layer/teambuilding-jpa/src/test/java/org/waldreg/repository/teambuilding/TeamBuildingRepositoryTest.java
  waldreg/repository-layer/teambuilding-jpa/src/test/java/org/waldreg/repository/teambuilding/repository/JpaTeamRepositoryTest.java
Labels: test, size/L

#361 feat : auth-jpa 작성 & refactor : 에러 핸들링
  waldreg/application-layer/auth-controller/src/main/java/org/waldreg/auth/AuthController.java
  waldreg/repository-layer/auth-jpa/build.gradle
  waldreg/repository-layer/auth-jpa/src/main/java/org/waldreg/repository/auth/AuthRepositoryServiceProvider.java
  waldreg/repository-layer/auth-jpa/src/main/java/org/waldreg/repository/auth/mapper/AuthRepositoryMapper.java
  waldreg/repository-layer/auth-jpa/src/main/java/org/waldreg/repository/auth/repository/JpaBoardRepository.java
  waldreg/repository-layer/auth-jpa/src/main/java/org/waldreg/repository/auth/repository/JpaCategoryRepository.java
  waldreg/repository-layer/auth-jpa/src/main/java/org/waldreg/repository/auth/repository/JpaCharacterRepository.java
  waldreg/repository-layer/auth-jpa/src/main/java/org/waldreg/repository/auth/repository/JpaCommentRepository.java
  waldreg/repository-layer/auth-jpa/src/main/java/org/waldreg/repository/auth/repository/JpaUserRepository.java
  waldreg/repository-layer/auth-jpa/src/test/java/org/waldreg/repository/auth/AuthRepositoryTest.java
  waldreg/repository-layer/auth-jpa/src/test/java/org/waldreg/repository/auth/JpaAuthTestInitializer.java
  waldreg/repository-layer/auth-jpa/src/test/java/org/waldreg/repository/auth/repository/JpaUserRepositoryTest.java
  waldreg/repository-layer/auth-jpa/src/test/resources/h2-application.properties
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/BoardRepositoryServiceProvider.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/auth/MemoryAuthRepository.java
  waldreg/service-layer/auth/src/main/java/org/waldreg/token/authenticator/TokenAuthenticator.java
  waldreg/service-layer/auth/src/main/java/org/waldreg/token/jwt/authenticator/JwtAuthenticator.java
  waldreg/service-layer/auth/src/main/java/org/waldreg/token/spi/AuthRepository.java
  waldreg/service-layer/auth/src/main/java/org/waldreg/token/spi/TokenUserFindUserIdAndPassword.java
  waldreg/settings.gradle
Labels: size/XL

#364 test : TeamUserRepositoryServiceProvider Test
  waldreg/application-layer/teambuilding-controller/build.gradle
  waldreg/repository-layer/teambuilding-jpa/src/main/java/org/waldreg/repository/teambuilding/team/TeamRepositoryServiceProvider.java
  waldreg/repository-layer/teambuilding-jpa/src/main/java/org/waldreg/repository/teambuilding/teamuser/TeamUserRepositoryServiceProvider.java
  waldreg/repository-layer/teambuilding-jpa/src/main/java/org/waldreg/repository/teambuilding/teamuser/mapper/TeamUserRepositoryMapper.java
  waldreg/repository-layer/teambuilding-jpa/src/main/java/org/waldreg/repository/teambuilding/teamuser/repository/JpaTeamUserRepository.java
  waldreg/repository-layer/teambuilding-jpa/src/test/java/org/waldreg/repository/teambuilding/TeamBuildingRepositoryTest.java
  waldreg/repository-layer/teambuilding-jpa/src/test/java/org/waldreg/repository/teambuilding/TeamRepositoryTest.java
  waldreg/repository-layer/teambuilding-jpa/src/test/java/org/waldreg/repository/teambuilding/TeamUserRepositoryTest.java
  waldreg/repository-layer/teambuilding-jpa/src/test/java/org/waldreg/repository/teambuilding/repository/JpaTeamBuildingRepositoryTest.java
  waldreg/repository-layer/teambuilding-jpa/src/test/java/org/waldreg/repository/teambuilding/repository/JpaTeamRepositoryTest.java
  waldreg/repository-layer/teambuilding-jpa/src/test/java/org/waldreg/repository/teambuilding/repository/JpaTeamUserRepositoryTest.java
Labels: test, size/L
