Repository waldreg/waldreg-api, pull requests merged in 2023-01, with the labels that each got.

#30 feat : 새로운 Character 생성 서비스 추가
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/config/PermissionConfiguration.java
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/dto/CharacterDto.java
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/dto/PermissionDto.java
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/exception/UnknownPermissionStatusException.java
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/management/CharacterManager.java
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/management/DefaultCharacterManager.java
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/management/PermissionChecker.java
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/permission/core/PermissionUnit.java
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/permission/management/PermissionUnitManager.java
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/spi/CharacterRepository.java
  waldreg/stable-service-layer/character/src/test/java/org/waldreg/character/permission/DefaultCharacterManagerTest.java
Labels: feature

#33 feat : 역할 단일 조회 서비스 추가
  waldreg/stable-service-layer/character/build/reports/tests/test/css/base-style.css
  waldreg/stable-service-layer/character/build/reports/tests/test/css/style.css
  waldreg/stable-service-layer/character/build/reports/tests/test/index.html
  waldreg/stable-service-layer/character/build/reports/tests/test/js/report.js
  waldreg/stable-service-layer/character/build/reports/tests/test/packages/org.waldreg.character.management.html
  waldreg/stable-service-layer/character/build/test-results/test/TEST-org.waldreg.character.management.DefaultCharacterManagerTest.xml
  waldreg/stable-service-layer/character/build/test-results/test/binary/output.bin
  waldreg/stable-service-layer/character/build/test-results/test/binary/output.bin.idx
  waldreg/stable-service-layer/character/build/test-results/test/binary/results.bin
  waldreg/stable-service-layer/character/build/tmp/compileJava/previous-compilation-data.bin
  waldreg/stable-service-layer/character/build/tmp/compileTestJava/previous-compilation-data.bin
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/management/CharacterManager.java
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/management/DefaultCharacterManager.java
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/spi/CharacterRepository.java
  waldreg/stable-service-layer/character/src/test/java/org/waldreg/character/management/DefaultCharacterManagerTest.java
Labels: feature

#34 feat : Character 목록 조회 서비스를 추가함
  waldreg/stable-service-layer/character/build/reports/tests/test/css/base-style.css
  waldreg/stable-service-layer/character/build/reports/tests/test/css/style.css
  waldreg/stable-service-layer/character/build/reports/tests/test/index.html
  waldreg/stable-service-layer/character/build/reports/tests/test/js/report.js
  waldreg/stable-service-layer/character/build/reports/tests/test/packages/org.waldreg.character.management.html
  waldreg/stable-service-layer/character/build/test-results/test/TEST-org.waldreg.character.management.DefaultCharacterManagerTest.xml
  waldreg/stable-service-layer/character/build/test-results/test/binary/output.bin
  waldreg/stable-service-layer/character/build/test-results/test/binary/output.bin.idx
  waldreg/stable-service-layer/character/build/test-results/test/binary/results.bin
  waldreg/stable-service-layer/character/build/tmp/compileJava/previous-compilation-data.bin
  waldreg/stable-service-layer/character/build/tmp/compileTestJava/previous-compilation-data.bin
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/management/CharacterManager.java
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/management/DefaultCharacterManager.java
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/spi/CharacterRepository.java
  waldreg/stable-service-layer/character/src/test/java/org/waldreg/character/management/DefaultCharacterManagerTest.java
Labels: feature

#35 feat : Character 수정 서비스 추가
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/management/CharacterManager.java
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/management/DefaultCharacterManager.java
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/spi/CharacterRepository.java
  waldreg/stable-service-layer/character/src/test/java/org/waldreg/character/management/DefaultCharacterManagerTest.java
Labels: feature, test

#36 feat : Character 삭제 기능 추가
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/management/CharacterManager.java
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/management/DefaultCharacterManager.java
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/spi/CharacterRepository.java
  waldreg/stable-service-layer/character/src/test/java/org/waldreg/character/management/DefaultCharacterManagerTest.java
Labels: feature, test

#37 feat : Util서비스 AnnotationExtractor 추가
  waldreg/.idea/gradle.xml
  waldreg/core-layer/util/build.gradle
  waldreg/core-layer/util/src/main/java/org/waldreg/util/AnnotationExtractor.java
  waldreg/settings.gradle
Labels: feature

#38 test : 유저 역할 인수테스트
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/user/UserAcceptanceTest.java
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/user/UserAcceptanceTestHelper.java
Labels: test

#27 test : 토큰 테스트 추가
  waldreg/service-layer/auth/build.gradle
  waldreg/service-layer/auth/src/test/java/org/waldreg/token/authenticator/JwtAuthenticatorTest.java
  waldreg/service-layer/auth/src/test/java/org/waldreg/token/authenticator/SuperAuthenticatorTest.java
  waldreg/service-layer/auth/src/test/java/org/waldreg/token/publisher/JwtPublisherTest.java
  waldreg/service-layer/auth/src/test/java/org/waldreg/token/publisher/SuperPublisherTest.java
Labels: test

#41 feat : 토큰 복호화 아이디 교환로직 UserIdContextHolder 추가
  waldreg/core-layer/util/src/main/java/org/waldreg/util/AnnotationExtractor.java
  waldreg/core-layer/util/src/main/java/org/waldreg/util/UserIdContextHolder.java
  waldreg/core-layer/util/src/test/java/org/waldreg/util/UserIdContextHolderTest.java
Labels: feature

#42 refactor : UserIdTokenContextHolder 리팩토링
  waldreg/core-layer/util/src/main/java/org/waldreg/util/DecryptedTokenContextHolder.java
  waldreg/core-layer/util/src/test/java/org/waldreg/util/DecryptedTokenContextHolderTest.java
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/management/CharacterManager.java
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/management/DefaultCharacterManager.java
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/spi/CharacterRepository.java
  waldreg/stable-service-layer/character/src/test/java/org/waldreg/character/management/DefaultCharacterManagerTest.java
Labels: refactor

#43 feat : Permission 어노테이션 검증 기능 추가
  waldreg/stable-service-layer/character/build.gradle
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/aop/CharacterInUserReadable.java
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/aop/PermissionVerifyAop.java
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/aop/annotation/PermissionVerifying.java
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/aop/behavior/VerifyingFailBehavior.java
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/exception/NoPermissionException.java
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/management/CharacterManager.java
Labels: feature

#44 chore : build파일 삭제
  waldreg/.idea/gradle.xml
  waldreg/service-layer/auth/build/reports/tests/test/css/base-style.css
  waldreg/service-layer/auth/build/reports/tests/test/css/style.css
  waldreg/service-layer/auth/build/reports/tests/test/index.html
  waldreg/service-layer/auth/build/reports/tests/test/js/report.js
  waldreg/service-layer/auth/build/reports/tests/test/packages/org.waldreg.token.authenticator.html
  waldreg/service-layer/auth/build/test-results/test/TEST-org.waldreg.token.authenticator.JwtAuthenticatorTest.xml
  waldreg/service-layer/auth/build/test-results/test/binary/output.bin
  waldreg/service-layer/auth/build/test-results/test/binary/output.bin.idx
  waldreg/service-layer/auth/build/test-results/test/binary/results.bin
  waldreg/service-layer/auth/build/tmp/compileJava/previous-compilation-data.bin
  waldreg/service-layer/auth/build/tmp/compileTestJava/previous-compilation-data.bin
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/aop/PermissionVerifyAop.java
Labels: chore

#45 feat : Character를 저장소에 저장 기능 추가
  waldreg/.idea/gradle.xml
  waldreg/repository-layer/memory-repository/build.gradle
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryCharacterStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/character/CharacterMapper.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/character/MemoryCharacterRepository.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/character/CharacterRepositoryTest.java
  waldreg/settings.gradle
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/exception/DuplicatedCharacterException.java
Labels: feature, test

#47 feat : 저장된 Character 조회 동작 추가
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryCharacterStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/character/CharacterMapper.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/character/MemoryCharacterRepository.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/character/CharacterRepositoryTest.java
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/exception/UnknownCharacterException.java
Labels: feature, test

#51 feat : Character 삭제 동작 추가
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryCharacterStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/character/MemoryCharacterRepository.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/character/CharacterRepositoryTest.java
Labels: feature, test

#55 fix : PermissionVerifying 이 적용되지 않던 오류 수정
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/aop/PermissionVerifyAop.java
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/aop/annotation/PermissionVerifying.java
Labels: fix bug

#56 fix : Decrypted 된 token이 없을경우 유의미한 예외를 반환하도록 수정함
  waldreg/core-layer/util/src/main/java/org/waldreg/util/DecryptedTokenContextHolder.java
  waldreg/core-layer/util/src/main/java/org/waldreg/util/exception/DecryptedTokenDoesNotExistException.java
Labels: fix bug

#54 feat : CharacterController 추가
  waldreg/.idea/gradle.xml
  waldreg/application-layer/acceptance/build.gradle
  waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/CharacterController.java
  waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/mapper/ControllerCharacterMapper.java
  waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/mapper/ControllerPermissionMapper.java
  waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/request/CharacterRequest.java
  waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/request/PermissionRequest.java
  waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/response/CharacterResponse.java
  waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/response/PermissionResponse.java
  waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/response/SpecifyStatusPermissionResponse.java
  waldreg/core-layer/util/src/main/java/org/waldreg/util/DecryptedTokenContextHolder.java
  waldreg/core-layer/util/src/main/java/org/waldreg/util/exception/DecryptedTokenDoesNotExistException.java
  waldreg/settings.gradle
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/aop/PermissionVerifyAop.java
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/aop/annotation/PermissionVerifying.java
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/permission/core/DefaultPermissionUnit.java
Labels: feature, chore

#57 refactor : util 패키지 리팩토링
  waldreg/.idea/gradle.xml
  waldreg/core-layer/util/src/main/java/org/waldreg/util/annotation/AnnotationExtractor.java
  waldreg/core-layer/util/src/main/java/org/waldreg/util/token/DecryptedTokenContext.java
  waldreg/core-layer/util/src/main/java/org/waldreg/util/token/DecryptedTokenContextGetter.java
  waldreg/core-layer/util/src/main/java/org/waldreg/util/token/DecryptedTokenContextHolder.java
  waldreg/core-layer/util/src/main/java/org/waldreg/util/token/DecryptedTokenContextResolver.java
  waldreg/core-layer/util/src/test/java/org/waldreg/util/DecryptedTokenContextTest.java
  waldreg/service-layer/auth/src/main/java/org/waldreg/token/jwt/authenticator/JwtAuthenticator.java
  waldreg/service-layer/auth/src/test/java/org/waldreg/token/authenticator/JwtAuthenticatorTest.java
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/aop/PermissionVerifyAop.java
Labels: refactor

#60 feat : 권한 확인 결과를 파라미터로 값을 전달하는 기능 추가
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/aop/PermissionVerifyAop.java
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/aop/parameter/PermissionVerifyState.java
Labels: feature

#53 feat : AuthRepository 테스트 및 구현
  waldreg/repository-layer/memory-repository/build.gradle
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryUserStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/auth/MemoryAuthRepository.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/character/AuthRepositoryTest.java
  waldreg/service-layer/auth/src/main/java/org/waldreg/token/dto/TokenUserDto.java
  waldreg/service-layer/auth/src/main/java/org/waldreg/token/exception/PasswordMissMatchException.java
  waldreg/service-layer/auth/src/main/java/org/waldreg/token/spi/AuthRepository.java
Labels: feature, test

#61 refactor : PermissionAcceptanceTestHelper url 파라미터 리팩토링
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/permission/PermissionAcceptanceTest.java
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/permission/PermissionAcceptanceTestHelper.java
Labels: refactor

#64 feat : 유저 전체 조회 서비스
  waldreg/service-layer/user/src/main/java/org/waldreg/user/exception/InvalidRangeException.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/management/DefaultUserManager.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/spi/UserRepository.java
  waldreg/service-layer/user/src/test/java/org/waldreg/user/management/UserServiceTest.java
Labels: feature, test

#63 feat : Application 시작시 "Admin" 역할이 없다면 추가하도록 설정
  waldreg/.idea/gradle.xml
  waldreg/application-layer/application-configurer/build.gradle
  waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/character/AdminCharacterConfigurer.java
  waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/character/AdminCharacterCreatedEvent.java
  waldreg/application-layer/application-configurer/src/test/java/org/waldreg/ConfigurerTestInitializer.java
  waldreg/application-layer/application-configurer/src/test/java/org/waldreg/config/character/AdminCharacterConfigurerTest.java
  waldreg/settings.gradle
Labels: feature, test

#67 fix : Admin, Guest 권한 삭제시 에러던지게 수정
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/aop/PermissionVerifyAop.java
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/management/DefaultCharacterManager.java
  waldreg/stable-service-layer/character/src/test/java/org/waldreg/character/aop/PermissionVerifierClient.java
  waldreg/stable-service-layer/character/src/test/java/org/waldreg/character/aop/PermissionVerifyAopTest.java
Labels: fix bug

#69 feat : Invalid id 예외 추가
  waldreg/repository-layer/memory-repository/build.gradle
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryUserStorage.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/exception/UnknownIdException.java
Labels: feature

#71 feat : Token인증 AOP 추가
  waldreg/.idea/gradle.xml
  waldreg/application-layer/auth-controller/build.gradle
  waldreg/application-layer/auth-controller/src/main/java/org/waldreg/auth/AuthController.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/auth/MemoryAuthRepository.java
  waldreg/service-layer/auth/build.gradle
  waldreg/service-layer/auth/src/main/java/org/waldreg/token/aop/AuthenticateAop.java
  waldreg/service-layer/auth/src/main/java/org/waldreg/token/aop/TokenUserFindById.java
  waldreg/service-layer/auth/src/main/java/org/waldreg/token/aop/annotation/Authenticating.java
  waldreg/service-layer/auth/src/main/java/org/waldreg/token/aop/annotation/HeaderPasswordAuthenticating.java
  waldreg/service-layer/auth/src/main/java/org/waldreg/token/aop/annotation/UserIdAuthenticating.java
  waldreg/service-layer/auth/src/main/java/org/waldreg/token/aop/behavior/AuthFailBehavior.java
  waldreg/service-layer/auth/src/main/java/org/waldreg/token/dto/TokenUserDto.java
  waldreg/service-layer/auth/src/main/java/org/waldreg/token/exception/UserIdMissMatchException.java
  waldreg/service-layer/auth/src/main/java/org/waldreg/token/jwt/authenticator/JwtAuthenticator.java
  waldreg/service-layer/auth/src/main/java/org/waldreg/token/spi/AuthRepository.java
  waldreg/service-layer/auth/src/main/java/org/waldreg/token/spi/TokenUserFindUserIdAndPassword.java
  waldreg/service-layer/auth/src/test/java/org/waldreg/token/aop/AuthenticateAopClient.java
  waldreg/service-layer/auth/src/test/java/org/waldreg/token/aop/AuthenticateAopTest.java
  waldreg/service-layer/auth/src/test/java/org/waldreg/token/authenticator/JwtAuthenticatorTest.java
Labels: feature, test

#72 feat : DecryptedContextResolverInterceptor 기본 등록 기능 추가
  waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/context/ContextConfigurer.java
  waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/context/DecryptedContextResolveInterceptor.java
Labels: feature

#76 feat : CharacterController예외를 잡는 기능을 추가함
  waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/globalexceptionadvice/ExceptionTemplate.java
  waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/globalexceptionadvice/RequestValidationAdvice.java
  waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/exceptionadvice/CharacterControllerAdvice.java
  waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/exceptionadvice/ExceptionTemplate.java
Labels: feature

#75 feat : 유저 전체 조회 레포지토리
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/user/User.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryUserStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/user/MemoryUserRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/user/UserMapper.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/user/UserRepositoryTest.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/management/DefaultUserManager.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/management/UserManager.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/spi/UserRepository.java
  waldreg/service-layer/user/src/test/java/org/waldreg/user/management/UserServiceTest.java
Labels: fix bug, feature, refactor, test

#77 fix : CharacterControllerAdvice 잘못된 파라미터 수정
  waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/exceptionadvice/CharacterControllerAdvice.java
Labels: fix bug

#80 feat : 애플리케이션 첫 실행시 Admin 유저를 기본 유저로 등록하도록 설정
  waldreg/application-layer/application-configurer/build.gradle
  waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/context/ContextConfigurer.java
  waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/user/AdminUserConfigurer.java
  waldreg/application-layer/application-configurer/src/test/java/org/waldreg/config/user/AdminUserConfigurerTest.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryUserStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/user/MemoryUserRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/user/UserMapper.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/character/AuthRepositoryTest.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/character/CharacterRepositoryTest.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/exception/UnknownUserIdException.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/management/DefaultUserManager.java
Labels: feature

#81 feat : 유저 서비스 관련 권한 등록
  waldreg/service-layer/user/src/main/java/org/waldreg/user/config/UserPermissionConfigurer.java
Labels: feature

#82 fix : AuthenticateAop에 Order가 적용
  waldreg/service-layer/auth/src/main/java/org/waldreg/token/aop/AuthenticateAop.java
Labels: fix bug

#83 feat : CharacterController에 인증 서비스 연동
  waldreg/application-layer/character-controller/build.gradle
  waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/CharacterController.java
Labels: feature

#84 feat : acceptance 모듈application-cofigurer 의존성 추가
  waldreg/application-layer/acceptance/build.gradle
Labels: feature

#86 fix : 토큰 타입과 토큰을 함께 전달하면 AuthenticateFail 에러가 나는 오류 수정
  waldreg/.idea/gradle.xml
  waldreg/application-layer/acceptance/build.gradle
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/authentication/AuthenticationAcceptanceTestHelper.java
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/permission/PermissionAcceptanceTest.java
  waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/context/DecryptedContextResolveInterceptor.java
  waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/version/ApiVersionConfigurer.java
  waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/version/ApiVersionSetInterceptor.java
  waldreg/application-layer/auth-controller/src/main/java/org/waldreg/auth/request/AuthTokenRequest.java
  waldreg/application-layer/auth-controller/src/main/java/org/waldreg/auth/response/AuthTokenResponse.java
  waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/mapper/ControllerUserMapper.java
  waldreg/service-layer/auth/src/main/java/org/waldreg/token/jwt/authenticator/JwtAuthenticator.java
  waldreg/service-layer/auth/src/test/java/org/waldreg/token/authenticator/JwtAuthenticatorTest.java
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/config/PermissionConfiguration.java
Labels: fix bug

#87 fix : Character Controller에 잘못된 Permission 이름이 들어간거 수정
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/authentication/AuthenticationAcceptanceTestHelper.java
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/permission/PermissionAcceptanceTest.java
  waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/user/AdminUserConfigurer.java
  waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/CharacterController.java
Labels: fix bug

#93 fix : 새로운 Character생성시 permission이 비어있다면, 없는권한으로 지정
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/permission/PermissionAcceptanceTest.java
  waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/globalexceptionadvice/RequestValidationAdvice.java
  waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/response/SpecifyStatusPermissionResponse.java
  waldreg/stable-service-layer/character/src/main/java/org/waldreg/character/management/DefaultCharacterManager.java
Labels: fix bug

#98 test : ADMIN, GUEST 역할 수정, 삭제 불가 인수테스트
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/permission/PermissionAcceptanceTest.java
Labels: test

#102 chore : Dockerfile 위치변경
  Dockerfile
  waldreg/Dockerfile
Labels: chore

#104 fix : CORS 수정
  waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/cors/CorsWebConfigurer.java
Labels: fix bug

#106 feat : Schedule, ScheduleRepeat 도메인을 추가함.
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/calendar/Schedule.java
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/calendar/ScheduleRepeat.java
Labels: feature

#107 feat : Schedule 도메인 추가
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/point/Advantage.java
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/point/Penalty.java
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/point/Point.java
Labels: feature

#108 refactor : user 도메인의 상, 벌점을 원시타입에서 객체로 바꿈
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/point/Advantage.java
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/point/Penalty.java
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/point/Point.java
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/user/User.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/user/MemoryUserRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/user/UserMapper.java
Labels: fix bug, refactor

#113 test : 상,벌점 서비스 인수테스트 작성
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/reward/RewardAcceptanceTest.java
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/reward/RewardAcceptanceTestHelper.java
Labels: test

#118 test : Schedule 인수 테스트 Initiate 추가
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/schedule/ScheduleAcceptanceTest.java
Labels: test

#119 test : RewardTag 생성 성공 테스트 추가
  waldreg/.idea/gradle.xml
  waldreg/service-layer/reward/build.gradle
  waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/tag/DefaultRewardTagManager.java
  waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/tag/RewardTagManager.java
  waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/tag/dto/RewardTagDto.java
  waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/tag/spi/RewardTagRepository.java
  waldreg/service-layer/reward/src/test/java/org/waldreg/reward/tag/RewardTagManagerTest.java
  waldreg/settings.gradle
Labels: test

#120 test : rewardtag 업데이트 테스트 추가
  waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/tag/DefaultRewardTagManager.java
  waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/tag/RewardTagManager.java
  waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/tag/spi/RewardTagRepository.java
  waldreg/service-layer/reward/src/test/java/org/waldreg/reward/tag/RewardTagManagerTest.java
Labels: test

#121 test : reward tag 목록 조회를 성공하는 테스트 추가
  waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/tag/DefaultRewardTagManager.java
  waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/tag/RewardTagManager.java
  waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/tag/spi/RewardTagRepository.java
  waldreg/service-layer/reward/src/test/java/org/waldreg/reward/tag/RewardTagManagerTest.java
Labels: test

#125 fix : reward tag 업데이트시 tag를 찾을 수 없으면 예외를 반환하도록 수정
  waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/tag/DefaultRewardTagManager.java
  waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/tag/exception/UnknownRewardTagException.java
  waldreg/service-layer/reward/src/test/java/org/waldreg/reward/tag/RewardTagManagerTest.java
Labels: fix bug

#129 fix : 특정 유저의 상,벌점 조회시 유저를 찾을 수 없는 예외 상황 수정
  waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/users/DefaultUsersRewardManager.java
  waldreg/service-layer/reward/src/test/java/org/waldreg/reward/users/UsersRewardManagerTest.java
Labels: fix bug

#130 fix : 유저의 상점을 삭제 하려고하는경우 발생할 수 있는 예외를 추가함
  waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/exception/UnknownRewardAssignTargetException.java
  waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/exception/UnknownRewardException.java
  waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/exception/UnknownRewardTargetException.java
  waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/users/DefaultUsersRewardManager.java
  waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/users/spi/repository/UsersRewardManagerRepository.java
  waldreg/service-layer/reward/src/test/java/org/waldreg/reward/users/UsersRewardManagerTest.java
Labels: fix bug

#131 feat : create new Schedule Service
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/schedule/ScheduleAcceptanceTestHelper.java
  waldreg/service-layer/schedule/build.gradle
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/dto/RepeatDto.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/dto/ScheduleDto.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/exception/ContentOverflowException.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/exception/InvalidDateFormatException.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/exception/InvalidRepeatException.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/exception/StartedAtIsAfterFinishAtException.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/management/DefaultScheduleManager.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/management/ScheduleManager.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/spi/ScheduleRepository.java
  waldreg/service-layer/schedule/src/test/java/org/waldreg/schedule/ScheduleServiceTest.java
  waldreg/settings.gradle
Labels: size/XL

#132 fix : RewardTag 도메인의 오타 수정및 id setter 추가
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/rewardtag/RewardTag.java
Labels: fix bug, size/S

#133 feat : RewardTag 저장소 추가 및 생성 서비스 추가
  waldreg/repository-layer/memory-repository/build.gradle
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/RewardTagStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/reward/MemoryRewardTagRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/reward/RewardTagMapper.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/reward/RewardTagRepositoryTest.java
Labels: size/L

#134 feat : RewardTag를 저장하는 메소드 추가
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/RewardTagStorage.java
Labels: feature, size/XS

#135 feat : 일정 조회 서비스
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/exception/InvalidSchedulePeriodException.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/exception/StartedAtIsAfterFinishAtException.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/management/DefaultScheduleManager.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/management/ScheduleManager.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/spi/ScheduleRepository.java
  waldreg/service-layer/schedule/src/test/java/org/waldreg/schedule/ScheduleServiceTest.java
Labels: feature, size/L

#136 feat : RewardTagStorage에 RUD를 추가함
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/RewardTagStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/reward/MemoryRewardTagRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/reward/RewardTagMapper.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/reward/RewardTagRepositoryTest.java
Labels: feature, size/M

#137 feat : 상벌점 존재 확인 로직 추가
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryRewardTagStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/reward/MemoryRewardTagRepository.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/reward/RewardTagRepositoryTest.java
Labels: size/M

#138 feat : 일정 수정 서비스
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/management/DefaultScheduleManager.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/management/ScheduleManager.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/spi/ScheduleRepository.java
  waldreg/service-layer/schedule/src/test/java/org/waldreg/schedule/ScheduleServiceTest.java
Labels: size/M

#139 feat : 상벌점 업데이트 로직을 추가함
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryRewardTagStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/reward/MemoryRewardTagRepository.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/reward/RewardTagRepositoryTest.java
Labels: size/M

#141 feat : RewardTag 삭제 로직 추가
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/reward/MemoryRewardTagRepository.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/reward/RewardTagRepositoryTest.java
Labels: size/S

#140 feat : 일정 삭제 서비스
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/management/DefaultScheduleManager.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/management/ScheduleManager.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/spi/ScheduleRepository.java
  waldreg/service-layer/schedule/src/test/java/org/waldreg/schedule/ScheduleServiceTest.java
Labels: size/M

#142 refactor : UsersRewardRepository이름을 변경함
  waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/users/DefaultUsersRewardManager.java
  waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/users/spi/repository/UsersRewardRepository.java
  waldreg/service-layer/reward/src/test/java/org/waldreg/reward/users/UsersRewardManagerTest.java
Labels: refactor, size/M

#143 test : 일정 조회 서비스
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/exception/UnknownScheduleException.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/management/DefaultScheduleManager.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/spi/repository/ScheduleRepository.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/spi/schedule/ScheduleIdExistChecker.java
  waldreg/service-layer/schedule/src/test/java/org/waldreg/schedule/ScheduleServiceTest.java
Labels: size/M

#145 fix : 일정 서비스 테스트
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/management/DefaultScheduleManager.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/spi/schedule/ScheduleIdExistChecker.java
  waldreg/service-layer/schedule/src/test/java/org/waldreg/schedule/ScheduleServiceTest.java
Labels: size/M

#144 refactor : RewardTagWrapper의 아이디를 setter로 설정하게 변경함
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/rewardtag/RewardTagWrapper.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryUserStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/usersreward/MemoryUsersRewardRepository.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/usersreward/MemoryUsersRewardRepositoryTest.java
Labels: refactor, size/L

#146 test : 일정 조회 실패 테스트
  waldreg/service-layer/schedule/src/test/java/org/waldreg/schedule/ScheduleServiceTest.java
Labels: size/M

#148 feat : 유저의 상점 목록 조회 로직 추가
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryUserStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/usersreward/MemoryUsersRewardRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/usersreward/UsersRewardMapper.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/usersreward/MemoryUsersRewardRepositoryTest.java
Labels: feature, test, size/M

#147 test : Update Schedule Service fail test
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/management/DefaultScheduleManager.java
  waldreg/service-layer/schedule/src/test/java/org/waldreg/schedule/ScheduleServiceTest.java
Labels: test, size/L

#149 feat : 특정 유저에게 부여된 상점 삭제 로직 추가
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryUserStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/usersreward/MemoryUsersRewardRepository.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/usersreward/MemoryUsersRewardRepositoryTest.java
Labels: size/M

#150 test : 유저 수정 실패 테스트 작성
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/schedule/ScheduleAcceptanceTest.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/management/DefaultScheduleManager.java
  waldreg/service-layer/schedule/src/test/java/org/waldreg/schedule/ScheduleServiceTest.java
Labels: size/L

#151 feat : 모든 유저가 받은 상점 초기화 로직 추가
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryUserStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/usersreward/MemoryUsersRewardRepository.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/usersreward/MemoryUsersRewardRepositoryTest.java
Labels: size/M

#152 test : 일정 수정 실패 테스트
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/management/DefaultScheduleManager.java
  waldreg/service-layer/schedule/src/test/java/org/waldreg/schedule/ScheduleServiceTest.java
Labels: size/M

#153 feat : 유저가 존재하는지 확인하는 로직추가
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/usersreward/MemoryUsersRewardRepository.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/usersreward/MemoryUsersRewardRepositoryTest.java
Labels: size/M

#154 feat : Reward manager 권한을 추가함
  waldreg/service-layer/reward/src/main/java/org/wadlreg/reward/config/RewardPermissionConfigurer.java
Labels: size/M

#155 test : 일정 수정 실패 테스트
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/management/DefaultScheduleManager.java
  waldreg/service-layer/schedule/src/test/java/org/waldreg/schedule/ScheduleServiceTest.java
Labels: size/M

#156 feat : reward tag 생성 컨트롤러 추가
  waldreg/.idea/gradle.xml
  waldreg/application-layer/acceptance/build.gradle
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/reward/RewardAcceptanceTest.java
  waldreg/application-layer/reward-controller/build.gradle
  waldreg/application-layer/reward-controller/src/main/java/org/waldreg/controller/reward/RewardController.java
  waldreg/application-layer/reward-controller/src/main/java/org/waldreg/controller/reward/mapper/ControllerRewardTagMapper.java
  waldreg/application-layer/reward-controller/src/main/java/org/waldreg/controller/reward/request/RewardTagRequest.java
  waldreg/settings.gradle
Labels: feature, size/L

#157 test : 일정 수정 실패 테스트
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/management/DefaultScheduleManager.java
  waldreg/service-layer/schedule/src/test/java/org/waldreg/schedule/ScheduleServiceTest.java
Labels: test, size/M

#158 test : 일정 삭제 실패 테스트 작성
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/management/DefaultScheduleManager.java
  waldreg/service-layer/schedule/src/test/java/org/waldreg/schedule/ScheduleServiceTest.java
Labels: size/M

#159 feat : reward tag목록을 조회하는 컨트롤러 추가
  waldreg/.idea/gradle.xml
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/reward/RewardAcceptanceTest.java
  waldreg/application-layer/reward-controller/src/main/java/org/waldreg/controller/reward/RewardController.java
  waldreg/application-layer/reward-controller/src/main/java/org/waldreg/controller/reward/mapper/ControllerRewardTagMapper.java
  waldreg/application-layer/reward-controller/src/main/java/org/waldreg/controller/reward/response/RewardTagResponse.java
Labels: feature, size/L

#160 feat : Reward tag 삭제 컨트롤러 추가
  waldreg/application-layer/reward-controller/src/main/java/org/waldreg/controller/reward/RewardController.java
Labels: feature, size/XS

#161 refactor : Reward controller 와 Users Reward controller를 분리함
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/reward/RewardAcceptanceTest.java
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/reward/RewardAcceptanceTestHelper.java
  waldreg/application-layer/reward-controller/src/main/java/org/waldreg/controller/reward/tag/RewardController.java
  waldreg/application-layer/reward-controller/src/main/java/org/waldreg/controller/reward/tag/mapper/ControllerRewardTagMapper.java
  waldreg/application-layer/reward-controller/src/main/java/org/waldreg/controller/reward/tag/request/RewardTagRequest.java
  waldreg/application-layer/reward-controller/src/main/java/org/waldreg/controller/reward/tag/response/RewardTagResponse.java
  waldreg/application-layer/reward-controller/src/main/java/org/waldreg/controller/reward/users/UsersRewardController.java
Labels: size/M

#162 feat : 모든 유저의 상점을 초기화하는 컨트롤러 추가
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/reward/RewardAcceptanceTest.java
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/reward/RewardAcceptanceTestHelper.java
  waldreg/application-layer/reward-controller/src/main/java/org/waldreg/controller/reward/users/UsersRewardController.java
  waldreg/application-layer/reward-controller/src/main/java/org/waldreg/controller/reward/users/mapper/ControllerUsersRewardMapper.java
  waldreg/application-layer/reward-controller/src/main/java/org/waldreg/controller/reward/users/response/RewardTagWrapperResponse.java
  waldreg/application-layer/reward-controller/src/main/java/org/waldreg/controller/reward/users/response/UsersRewardTagResponse.java
Labels: size/L

#163 feat : 일정 생성 성공 레포지토리
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/calendar/Schedule.java
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/calendar/ScheduleRepeat.java
  waldreg/repository-layer/memory-repository/build.gradle
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryScheduleStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/schedule/MemoryScheduleRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/schedule/ScheduleMapper.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/schedule/ScheduleRepositoryTest.java
Labels: feature, test, size/L

#166 refactor : Reward 인수테스트 수정
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/reward/RewardAcceptanceTest.java
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/reward/RewardAcceptanceTestHelper.java
  waldreg/application-layer/application-configurer/src/main/java/org/waldreg/config/cors/CorsWebConfigurer.java
  waldreg/application-layer/reward-controller/src/main/java/org/waldreg/controller/reward/exceptionadvice/RewardControllerAdvice.java
  waldreg/application-layer/reward-controller/src/main/java/org/waldreg/controller/reward/tag/response/RewardTagResponse.java
  waldreg/application-layer/reward-controller/src/main/java/org/waldreg/controller/reward/users/UsersRewardController.java
Labels: fix bug, refactor, size/M

#165 test : 일정 생성 레포지토리 테스트
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/schedule/MemoryScheduleRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/schedule/ScheduleMapper.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/schedule/ScheduleRepositoryTest.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/management/DefaultScheduleManager.java
Labels: size/M

#167 feat : Id기반 인증 AOP추가
  waldreg/application-layer/reward-controller/src/main/java/org/waldreg/controller/reward/users/UsersRewardController.java
  waldreg/service-layer/auth/src/main/java/org/waldreg/token/aop/AuthenticateAop.java
  waldreg/service-layer/auth/src/main/java/org/waldreg/token/aop/annotation/IdAuthenticating.java
  waldreg/service-layer/auth/src/main/java/org/waldreg/token/aop/parameter/AuthenticateVerifyState.java
  waldreg/service-layer/auth/src/main/java/org/waldreg/token/exception/IdMissMatchException.java
Labels: feature, size/L

#170 test : read Schedule By Term Repository Test
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryScheduleStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/schedule/MemoryScheduleRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/schedule/ScheduleMapper.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/schedule/ScheduleRepositoryTest.java
Labels: size/L

#171 test : 특정 일정 조회 레포지토리 성공 테스트
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryScheduleStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/schedule/MemoryScheduleRepository.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/schedule/ScheduleMapper.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/schedule/ScheduleRepositoryTest.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/management/DefaultScheduleManager.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/spi/ScheduleRepository.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/spi/schedule/ScheduleIdExistChecker.java
  waldreg/service-layer/schedule/src/test/java/org/waldreg/schedule/ScheduleServiceTest.java
Labels: size/L

#172 test : 일정 수정 성공 레포지토리 테스트
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryScheduleStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/schedule/MemoryScheduleRepository.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/schedule/ScheduleRepositoryTest.java
Labels: test, size/L

#173 test : 일정 삭제 레포지토리 성공 테스트
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/MemoryScheduleStorage.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/schedule/MemoryScheduleRepository.java
  waldreg/repository-layer/memory-repository/src/test/java/org/waldreg/repository/schedule/ScheduleRepositoryTest.java
Labels: size/M

#174 refactor : Request, Response
  waldreg/application-layer/acceptance/build.gradle
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/schedule/ScheduleAcceptanceTest.java
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/schedule/ScheduleAcceptanceTestHelper.java
  waldreg/application-layer/schedule-controller/build.gradle
  waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/ScheduleController.java
  waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/request/ScheduleRepeatRequest.java
  waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/request/ScheduleRequest.java
  waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/response/ScheduleListResponse.java
  waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/response/ScheduleRepeatResponse.java
  waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/response/ScheduleResponse.java
  waldreg/settings.gradle
Labels: refactor, size/XXL

#175 feat : create new Schedule Controller
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/schedule/ScheduleAcceptanceTest.java
  waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/ScheduleController.java
  waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/mapper/ControllerScheduleMapper.java
  waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/request/ScheduleRequest.java
  waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/response/ScheduleListResponse.java
  waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/response/ScheduleResponse.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/schedule/ScheduleMapper.java
Labels: feature, size/L

#177 feat : read Specific Schedule Controller
  waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/ScheduleController.java
Labels: feature, size/XS

#178 feat : 특정 일정 조회 Controller
  waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/ScheduleController.java
Labels: size/S

#176 fix : Board, Comment, Reaction 도메인 변경
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/board/Board.java
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/board/comment/Comment.java
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/board/reaction/Reaction.java
Labels: size/M

#179 feat : 일정 삭제 Controller
  waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/ScheduleController.java
Labels: feature, size/XS

#180 feat : 인증 및 새로운 일정 생성 권한 추가
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/schedule/ScheduleAcceptanceTest.java
  waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/ScheduleController.java
  waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/UserController.java
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/schedule/MemoryScheduleRepository.java
  waldreg/service-layer/schedule/build.gradle
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/config/SchedulePermissionConfigurer.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/management/DefaultScheduleManager.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/config/UserPermissionConfigurer.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/management/DefaultUserManager.java
Labels: feature, size/L

#182 feat : 인증 및 일정 수정 권한 추가
  waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/ScheduleController.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/config/SchedulePermissionConfigurer.java
Labels: feature, size/S

#183 feat : 일정 삭제 권한 및 인증 추가
  waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/ScheduleController.java
  waldreg/service-layer/schedule/src/main/java/org/waldreg/schedule/config/SchedulePermissionConfigurer.java
Labels: feature, size/S

#184 feat : 일정 조회 인증 추가
  waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/ScheduleController.java
  waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/exceptionadvice/ExceptionTemplate.java
  waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/exceptionadvice/ScheduleControllerAdvice.java
Labels: feature, size/M

#185 feat : InvalidDateFormatException Handler
  waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/exceptionadvice/ScheduleControllerAdvice.java
Labels: feature, size/S

#186 feat : InvalidRepeatException Handler 추가
  waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/exceptionadvice/ScheduleControllerAdvice.java
Labels: feature, size/S

#187 feat : InvalidSchedulePeriodExcpetion Handler
  waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/exceptionadvice/ScheduleControllerAdvice.java
Labels: feature, size/S

#188 feat : UnknownScheduleException Handler 추가
  waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/exceptionadvice/ScheduleControllerAdvice.java
Labels: feature, size/S
