Repository waldreg/waldreg-api, pull requests merged in 2023-03, with the labels that each got.

#367 feat : board 관련 예외를 추가함
  waldreg/application-layer/board-controller/src/main/java/org/waldreg/controller/board/comment/request/CommentRequest.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/board/management/DefaultBoardManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/category/management/DefaultCategoryManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/comment/management/DefaultCommentManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/exception/BoardTitleOverFlowException.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/exception/CategoryNameOverFlowException.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/exception/ContentOverFlowException.java
Labels: size/M

#365 feat : joining pool jpa 작성완료 & 로직 이동
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/user/UserJoiningPool.java
  waldreg/repository-layer/auth-jpa/src/test/java/org/waldreg/repository/auth/repository/JpaUserRepositoryTest.java
  waldreg/repository-layer/joiningpool-jpa/build.gradle
  waldreg/repository-layer/joiningpool-jpa/src/main/java/org/waldreg/repository/joiningpool/JoiningPoolRepositoryServiceProvider.java
  waldreg/repository-layer/joiningpool-jpa/src/main/java/org/waldreg/repository/joiningpool/mapper/JoiningPoolMapper.java
  waldreg/repository-layer/joiningpool-jpa/src/main/java/org/waldreg/repository/joiningpool/repository/JpaJoiningPoolRepository.java
  waldreg/repository-layer/joiningpool-jpa/src/main/java/org/waldreg/repository/joiningpool/repository/JpaUserRepository.java
  waldreg/repository-layer/joiningpool-jpa/src/test/java/org/waldreg/repository/joiningpool/JoiningPoolTest.java
  waldreg/repository-layer/joiningpool-jpa/src/test/java/org/waldreg/repository/joiningpool/JpaJoiningPoolTestInitializer.java
  waldreg/repository-layer/joiningpool-jpa/src/test/java/org/waldreg/repository/joiningpool/repository/JpaJoiningPoolTest.java
  waldreg/repository-layer/joiningpool-jpa/src/test/resources/h2-application.properties
  waldreg/repository-layer/memory-repository/src/main/java/org/waldreg/repository/user/MemoryJoiningPoolRepository.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/management/joiningpool/DefaultJoiningPoolManager.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/spi/JoiningPoolRepository.java
  waldreg/settings.gradle
Labels: size/XL

#369 feat : boardUserRepository 구현체 작성
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/BoardUserServiceProvider.java
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/mapper/BoardUserRepositoryMapper.java
  waldreg/repository-layer/board-jpa/src/test/java/org/waldreg/repository/board/BoardUserRepositoryTest.java
Labels: size/L

#370 fix : commentInBoardRepository 구현체 생성
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/CommentRepositoryServiceProvider.java
  waldreg/repository-layer/board-jpa/src/test/java/org/waldreg/repository/board/CommentRepositoryTest.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/comment/management/DefaultCommentManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/comment/spi/CommentInBoardRepository.java
Labels: size/XXL

#371 feat : user exceptionadvice (ContextOverflowException) 추가
  waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/exceptionadvice/UserControllerAdvice.java
Labels: fix bug

#372 Board exception advice 추가
  waldreg/application-layer/board-controller/src/main/java/org/waldreg/controller/board/exceptionadvice/BoardControllerAdvice.java
Labels: size/S

#374 feat : xss filtering
  waldreg/application-layer/application-configurer/src/test/resources/application.properties
  waldreg/application-layer/schedule-controller/build.gradle
  waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/ScheduleController.java
  waldreg/application-layer/teambuilding-controller/build.gradle
  waldreg/application-layer/teambuilding-controller/src/main/java/org/waldreg/controller/teambuilding/TeamBuildingController.java
  waldreg/application-layer/user-controller/build.gradle
  waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/joiningpool/JoiningPoolController.java
  waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/UserController.java
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/user/UserInfo.java
  waldreg/repository-layer/attendance-jpa/src/main/java/org/waldreg/repository/attendance/repository/JpaAttendanceUserRepository.java
  waldreg/repository-layer/attendance-jpa/src/main/java/org/waldreg/repository/attendance/type/AttendanceTypeRepositoryServiceProvider.java
  waldreg/repository-layer/attendance-jpa/src/main/java/org/waldreg/repository/attendance/type/repository/JpaAttendanceTypeRepository.java
  waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/JpaAttendanceTestInitializer.java
  waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/helper/TestJpaCharacterRepository.java
  waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/repository/JpaAttendanceRepositoryTest.java
  waldreg/repository-layer/auth-jpa/src/test/java/org/waldreg/repository/auth/repository/JpaUserRepositoryTest.java
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/BoardUserServiceProvider.java
  waldreg/repository-layer/board-jpa/src/test/java/org/waldreg/repository/board/BoardUserRepositoryTest.java
  waldreg/repository-layer/board-jpa/src/test/java/org/waldreg/repository/board/CommentRepositoryTest.java
  waldreg/repository-layer/character-jpa/build.gradle
  waldreg/repository-layer/character-jpa/src/main/java/org/waldreg/repository/character/repository/JpaCharacterRepository.java
  waldreg/repository-layer/character-jpa/src/main/java/org/waldreg/repository/character/repository/JpaUserRepository.java
  waldreg/repository-layer/character-jpa/src/test/java/org/waldreg/repository/character/repository/JpaCharacterRepositoryTest.java
  waldreg/repository-layer/joiningpool-jpa/build.gradle
  waldreg/repository-layer/joiningpool-jpa/src/main/java/org/waldreg/repository/joiningpool/JoiningPoolRepositoryServiceProvider.java
  waldreg/repository-layer/joiningpool-jpa/src/main/java/org/waldreg/repository/joiningpool/mapper/JoiningPoolMapper.java
  waldreg/repository-layer/joiningpool-jpa/src/main/java/org/waldreg/repository/joiningpool/repository/JpaJoiningPoolRepository.java
  waldreg/repository-layer/joiningpool-jpa/src/main/java/org/waldreg/repository/joiningpool/repository/JpaUserRepository.java
  waldreg/repository-layer/joiningpool-jpa/src/test/java/org/waldreg/repository/joiningpool/JoiningPoolTest.java
  waldreg/repository-layer/joiningpool-jpa/src/test/java/org/waldreg/repository/joiningpool/JpaJoiningPoolTestInitializer.java
  waldreg/repository-layer/joiningpool-jpa/src/test/java/org/waldreg/repository/joiningpool/repository/JpaJoiningPoolTest.java
  waldreg/repository-layer/joiningpool-jpa/src/test/resources/h2-application.properties
  waldreg/repository-layer/reward-jpa/src/main/java/org/waldreg/repository/reward/repository/JpaAttendanceTypeRewardRepository.java
  waldreg/repository-layer/user-jpa/src/main/java/org/waldreg/repository/user/repository/JpaAttendanceRepository.java
  waldreg/repository-layer/user-jpa/src/main/java/org/waldreg/repository/user/repository/JpaAttendanceUserRepository.java
  waldreg/service-layer/attendance/src/main/java/org/waldreg/attendance/type/spi/AttendanceTypeRepository.java
  waldreg/service-layer/auth/src/test/java/org/waldreg/token/authenticator/JwtAuthenticatorTest.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/exception/BoardTitleOverFlowException.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/exception/CategoryNameOverFlowException.java
Labels: feature, size/XXL

#376 jpa exist query수정
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/board/reaction/Reaction.java
  waldreg/repository-layer/auth-jpa/src/main/java/org/waldreg/repository/auth/AuthRepositoryServiceProvider.java
  waldreg/repository-layer/auth-jpa/src/main/java/org/waldreg/repository/auth/repository/JpaUserRepository.java
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/CategoryRepositoryServiceProvider.java
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/repository/JpaCategoryRepository.java
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/repository/JpaReactionUserRepository.java
  waldreg/repository-layer/board-jpa/src/test/java/org/waldreg/repository/board/repository/JpaBoardRepositoryTest.java
  waldreg/repository-layer/board-jpa/src/test/java/org/waldreg/repository/board/repository/JpaCategoryRepositoryTest.java
  waldreg/repository-layer/board-jpa/src/test/java/org/waldreg/repository/board/repository/JpaCommentRepositoryTest.java
  waldreg/repository-layer/board-jpa/src/test/java/org/waldreg/repository/board/repository/JpaReactionUserRepositoryTest.java
  waldreg/repository-layer/joiningpool-jpa/src/main/java/org/waldreg/repository/joiningpool/repository/JpaJoiningPoolRepository.java
  waldreg/repository-layer/joiningpool-jpa/src/main/java/org/waldreg/repository/joiningpool/repository/JpaUserRepository.java
  waldreg/repository-layer/teambuilding-jpa/src/main/java/org/waldreg/repository/teambuilding/teamuser/TeamUserRepositoryServiceProvider.java
  waldreg/repository-layer/teambuilding-jpa/src/main/java/org/waldreg/repository/teambuilding/teamuser/repository/JpaTeamUserRepository.java
  waldreg/repository-layer/teambuilding-jpa/src/test/java/org/waldreg/repository/teambuilding/repository/JpaTeamUserRepositoryTest.java
  waldreg/repository-layer/user-jpa/src/main/java/org/waldreg/repository/user/UserRepositoryServiceProvider.java
  waldreg/repository-layer/user-jpa/src/main/java/org/waldreg/repository/user/repository/JpaCharacterRepository.java
  waldreg/repository-layer/user-jpa/src/main/java/org/waldreg/repository/user/repository/JpaUserRepository.java
  waldreg/repository-layer/user-jpa/src/test/java/org/waldreg/repository/user/repository/JpaUserRepositoryTest.java
Labels: size/M

#377 Xss 추가
  waldreg/application-layer/acceptance/build.gradle
  waldreg/application-layer/application-configurer/src/test/resources/application.properties
  waldreg/application-layer/attendance-controller/build.gradle
  waldreg/application-layer/attendance-controller/src/main/java/org/waldreg/controller/attendance/management/AttendanceController.java
  waldreg/application-layer/attendance-controller/src/main/java/org/waldreg/controller/attendance/valid/AttendanceValidController.java
  waldreg/application-layer/attendance-controller/src/main/java/org/waldreg/controller/attendance/waiver/WaiverController.java
  waldreg/application-layer/auth-controller/build.gradle
  waldreg/application-layer/auth-controller/src/main/java/org/waldreg/auth/AuthController.java
  waldreg/application-layer/board-controller/build.gradle
  waldreg/application-layer/board-controller/src/main/java/org/waldreg/controller/board/board/BoardController.java
  waldreg/application-layer/board-controller/src/main/java/org/waldreg/controller/board/category/CategoryController.java
  waldreg/application-layer/board-controller/src/main/java/org/waldreg/controller/board/comment/CommentController.java
  waldreg/application-layer/board-controller/src/main/java/org/waldreg/controller/board/file/FileController.java
  waldreg/application-layer/board-controller/src/main/java/org/waldreg/controller/board/reaction/ReactionController.java
  waldreg/application-layer/character-controller/build.gradle
  waldreg/application-layer/character-controller/src/main/java/org/waldreg/controller/character/CharacterController.java
  waldreg/application-layer/reward-controller/build.gradle
  waldreg/application-layer/reward-controller/src/main/java/org/waldreg/controller/reward/tag/RewardController.java
  waldreg/application-layer/reward-controller/src/main/java/org/waldreg/controller/reward/users/UsersRewardController.java
  waldreg/application-layer/schedule-controller/build.gradle
  waldreg/application-layer/schedule-controller/src/main/java/org/waldreg/controller/schedule/ScheduleController.java
  waldreg/application-layer/teambuilding-controller/build.gradle
  waldreg/application-layer/teambuilding-controller/src/main/java/org/waldreg/controller/teambuilding/TeamBuildingController.java
  waldreg/application-layer/user-controller/build.gradle
  waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/joiningpool/JoiningPoolController.java
  waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/UserController.java
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/user/UserInfo.java
  waldreg/repository-layer/attendance-jpa/src/main/java/org/waldreg/repository/attendance/repository/JpaAttendanceUserRepository.java
  waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/JpaAttendanceTestInitializer.java
  waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/helper/TestJpaCharacterRepository.java
  waldreg/repository-layer/attendance-jpa/src/test/java/org/waldreg/repository/attendance/repository/JpaAttendanceRepositoryTest.java
  waldreg/repository-layer/auth-jpa/src/test/java/org/waldreg/repository/auth/repository/JpaUserRepositoryTest.java
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/BoardUserServiceProvider.java
  waldreg/repository-layer/board-jpa/src/test/java/org/waldreg/repository/board/BoardUserRepositoryTest.java
  waldreg/repository-layer/board-jpa/src/test/java/org/waldreg/repository/board/CommentRepositoryTest.java
  waldreg/repository-layer/character-jpa/build.gradle
  waldreg/repository-layer/character-jpa/src/main/java/org/waldreg/repository/character/repository/JpaCharacterRepository.java
  waldreg/repository-layer/character-jpa/src/main/java/org/waldreg/repository/character/repository/JpaUserRepository.java
  waldreg/repository-layer/character-jpa/src/test/java/org/waldreg/repository/character/repository/JpaCharacterRepositoryTest.java
  waldreg/repository-layer/joiningpool-jpa/build.gradle
  waldreg/repository-layer/joiningpool-jpa/src/main/java/org/waldreg/repository/joiningpool/mapper/JoiningPoolMapper.java
  waldreg/repository-layer/joiningpool-jpa/src/test/java/org/waldreg/repository/joiningpool/JoiningPoolTest.java
  waldreg/repository-layer/joiningpool-jpa/src/test/java/org/waldreg/repository/joiningpool/JpaJoiningPoolTestInitializer.java
  waldreg/repository-layer/joiningpool-jpa/src/test/resources/h2-application.properties
  waldreg/repository-layer/reward-jpa/src/main/java/org/waldreg/repository/reward/repository/JpaAttendanceTypeRewardRepository.java
  waldreg/repository-layer/user-jpa/src/main/java/org/waldreg/repository/user/repository/JpaAttendanceRepository.java
  waldreg/repository-layer/user-jpa/src/main/java/org/waldreg/repository/user/repository/JpaAttendanceUserRepository.java
  waldreg/service-layer/auth/src/test/java/org/waldreg/token/authenticator/JwtAuthenticatorTest.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/exception/BoardTitleOverFlowException.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/exception/CategoryNameOverFlowException.java
Labels: size/XXL

#379 fix : Table생성시 모두 대문자로 생성되도록 수정
  .env
  docker-compose.yml
Labels: size/XS

#381 Create LICENSE
  LICENSE
Labels: size/L

#382 fix : 유저 전체 조회 쿼리가 DBMS에 특화되는 문제 수정
  LICENSE
  README.md
  waldreg/repository-layer/user-jpa/src/main/java/org/waldreg/repository/user/UserRepositoryCommander.java
  waldreg/repository-layer/user-jpa/src/main/java/org/waldreg/repository/user/UserRepositoryServiceProvider.java
  waldreg/repository-layer/user-jpa/src/main/java/org/waldreg/repository/user/repository/JpaUserRepository.java
  waldreg/repository-layer/user-jpa/src/test/java/org/waldreg/repository/user/UserRepositoryTest.java
  waldreg/repository-layer/user-jpa/src/test/java/org/waldreg/repository/user/repository/JpaUserRepositoryTest.java
Labels: size/L

#384 fix : board jpa 의 페이징 쿼리 수정
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/BoardCommander.java
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/BoardRepositoryServiceProvider.java
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/CategoryRepositoryServiceProvider.java
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/CommentCommander.java
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/CommentRepositoryServiceProvider.java
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/repository/JpaBoardRepository.java
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/repository/JpaCommentRepository.java
  waldreg/repository-layer/board-jpa/src/test/java/org/waldreg/repository/board/BoardRepositoryTest.java
  waldreg/repository-layer/board-jpa/src/test/java/org/waldreg/repository/board/CategoryRepositoryTest.java
  waldreg/repository-layer/board-jpa/src/test/java/org/waldreg/repository/board/CommentRepositoryTest.java
  waldreg/repository-layer/board-jpa/src/test/java/org/waldreg/repository/board/repository/JpaBoardRepositoryTest.java
  waldreg/repository-layer/board-jpa/src/test/java/org/waldreg/repository/board/repository/JpaCommentRepositoryTest.java
Labels: size/L

#387 fix : board views 버그 수정
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/board/Board.java
  waldreg/repository-layer/board-jpa/src/main/java/org/waldreg/repository/board/BoardRepositoryServiceProvider.java
Labels: size/XS

#388 feat : 상,벌점 태그를 한번이라도 받은 유저 목록 조회 인수테스트 작성
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/reward/RewardAcceptanceTest.java
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/reward/RewardAcceptanceTestHelper.java
Labels: size/L

#391 feat : JpaRepository에 상벌점 받은 유저 조회 쿼리 추가
  waldreg/repository-layer/reward-jpa/src/main/java/org/waldreg/repository/reward/repository/JpaRewardTagWrapperRepository.java
  waldreg/repository-layer/reward-jpa/src/main/java/org/waldreg/repository/reward/user/UsersRewardRepositoryServiceProvider.java
  waldreg/repository-layer/reward-jpa/src/test/java/org/waldreg/repository/reward/repository/JpaRewardUserRepositoryTest.java
Labels: size/M

#392 feat : 상벌점태그 갖고있는유저확인 서비스 완성
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/reward/RewardAcceptanceTest.java
  waldreg/application-layer/reward-controller/src/main/java/org/waldreg/controller/reward/users/UsersRewardController.java
Labels: size/M

#396 feat : 특정 유저 목록 조회 성공/실패 테스트 및 구현체 작성
  waldreg/repository-layer/user-jpa/src/main/java/org/waldreg/repository/user/UserRepositoryServiceProvider.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/management/user/DefaultUserManager.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/management/user/UserManager.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/spi/UserRepository.java
  waldreg/service-layer/user/src/test/java/org/waldreg/user/management/UserServiceTest.java
Labels: feature, size/M

#397 feat : 특정 유저 목록 조회 레포지토리 구현
  waldreg/repository-layer/user-jpa/src/main/java/org/waldreg/repository/user/UserRepositoryServiceProvider.java
  waldreg/repository-layer/user-jpa/src/test/java/org/waldreg/repository/user/UserRepositoryTest.java
  waldreg/service-layer/user/src/main/java/org/waldreg/user/management/user/DefaultUserManager.java
Labels: feature, size/M

#398 feat : 특정 유저 목록 조회 controller 작성 및 인수테스트 통과
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/user/UserAcceptanceTest.java
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/user/UserAcceptanceTestHelper.java
  waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/UserController.java
  waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/response/SpecificUserListResponse.java
Labels: feature, size/M

#399 feat : 특정 카테고리 조회 인수테스트 작성
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/board/BoardAcceptanceTest.java
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/board/BoardAcceptanceTestHelper.java
  waldreg/application-layer/board-controller/src/main/java/org/waldreg/controller/board/category/CategoryController.java
  waldreg/application-layer/board-controller/src/main/java/org/waldreg/controller/board/category/mapper/ControllerCategoryMapper.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/category/management/CategoryManager.java
  waldreg/service-layer/board/src/main/java/org/waldreg/board/category/management/DefaultCategoryManager.java
  waldreg/service-layer/board/src/test/java/org/waldreg/board/category/CategoryManagerTest.java
Labels: size/L

#401 fix : user 인수테스트 전화번호 수정
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/user/UserAcceptanceTest.java
Labels: size/XS

#403 fix : 전화번호 정규식 수정
  waldreg/application-layer/acceptance/src/test/java/org/waldreg/acceptance/user/UserAcceptanceTest.java
  waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/joiningpool/request/UserRequest.java
  waldreg/application-layer/user-controller/src/main/java/org/waldreg/controller/user/request/UpdateUserRequest.java
Labels: fix bug, size/XS

#409 feat : 홈화면 게시글 수정 성공 테스트 및 구현
  waldreg/service-layer/home/src/main/java/org/waldreg/home/service/homecontent/management/DefaultHomeManager.java
  waldreg/service-layer/home/src/test/java/org/waldreg/home/home/HomeServiceTest.java
Labels: feature, test, size/S

#410 feat : DB에서 홈화면 게시글 조회 서비스 생성
  waldreg/repository-layer/home-jpa/src/main/java/org/waldreg/repository/home/HomeRepositoryServiceProvider.java
  waldreg/repository-layer/home-jpa/src/main/java/org/waldreg/repository/home/repository/HomeJpaRepository.java
  waldreg/repository-layer/home-jpa/src/test/java/org/waldreg/repository/home/HomeRepositoryServiceProviderTest.java
  waldreg/repository-layer/home-jpa/src/test/java/org/waldreg/repository/home/JpaHomeTestInitializer.java
  waldreg/repository-layer/home-jpa/src/test/resources/h2-application.properties
Labels: size/L

#411 feat : permission config 추가
  waldreg/service-layer/home/src/main/java/org/waldreg/home/service/homecontent/config/HomePermissionConfigurer.java
Labels: feature, size/S

#413 feat : 색깔 조회 성공 서비스 테스트 및 구현
  waldreg/service-layer/home/src/main/java/org/waldreg/home/service/color/ColorManager.java
  waldreg/service-layer/home/src/main/java/org/waldreg/home/service/color/dto/ColorDto.java
  waldreg/service-layer/home/src/main/java/org/waldreg/home/service/color/management/ColorManager.java
  waldreg/service-layer/home/src/main/java/org/waldreg/home/service/color/management/DefaultColorManager.java
  waldreg/service-layer/home/src/test/java/org/waldreg/home/color/ColorServiceTest.java
  waldreg/service-layer/home/src/test/java/org/waldreg/home/home/HomeServiceTest.java
Labels: feature, test, size/L

#412 feat : DB에 홈 게시글 수정 서비스 추가
  waldreg/repository-layer/home-jpa/src/main/java/org/waldreg/repository/home/ColorRepositoryServiceProvider.java
  waldreg/repository-layer/home-jpa/src/main/java/org/waldreg/repository/home/HomeRepositoryServiceProvider.java
  waldreg/repository-layer/home-jpa/src/main/java/org/waldreg/repository/home/repository/ColorJpaRepository.java
  waldreg/repository-layer/home-jpa/src/test/java/org/waldreg/repository/home/ColorRepositoryServiceProviderTest.java
  waldreg/repository-layer/home-jpa/src/test/java/org/waldreg/repository/home/HomeRepositoryServiceProviderTest.java
Labels: size/M

#414 feat : 애플리케이션 색깔 수정 성공 서비스 테스트 및 구현
  waldreg/service-layer/home/src/main/java/org/waldreg/home/service/color/management/DefaultColorManager.java
  waldreg/service-layer/home/src/test/java/org/waldreg/home/color/ColorServiceTest.java
Labels: feature, test, size/S

#415 feat : DB에서 Color 수정 및 조회 서비스 추가
  waldreg/domain-layer/domain/src/main/java/org/waldreg/domain/home/ApplicationColor.java
  waldreg/repository-layer/home-jpa/src/main/java/org/waldreg/repository/home/ColorRepositoryServiceProvider.java
  waldreg/repository-layer/home-jpa/src/main/java/org/waldreg/repository/home/repository/ColorJpaRepository.java
  waldreg/repository-layer/home-jpa/src/test/java/org/waldreg/repository/home/ColorRepositoryServiceProviderTest.java
Labels: size/M

#417 fix : 초기 홈화면 글, 색깔 설정 클래스 추가
  waldreg/repository-layer/home-jpa/src/main/java/org/waldreg/repository/home/config/HomeInitializer.java
Labels: size/M

#416 feat : color Configurer 추가
  waldreg/service-layer/home/src/main/java/org/waldreg/home/service/config/HomePermissionConfigurer.java
Labels: size/XS
